### PR TITLE
Configurable retries

### LINKED ISSUE #2723: Set the maximum number of retries for a job on a pipeline basis
**What is the ask?**

Set the maximum number of retries for a job on a pipeline basis.

**What is the goal / desired outcome?**

Set this retry number to 1 so that the job is not retried.  The problem is that if you have a human error on a job that takes 3 hours to complete, you don't want to wait 9 hours to see that error. 

**If there is a way to accomplish this today via workaround, what does that require?**

No workaround, the value is hard coded to 3 in src/server/worker/api_server.go.

----

To do this, I propose to add a new int32 field on CreatePipelineRequest and PipelineInfo named max_retries.  If negative or 0, defaults to 3; otherwise, this is the maximum number of retries.

### PR DESCRIPTION
**Pull request by jdoliner**
Fixes #2723

### CODE REVIEW

**Comment by JoeyZwicker** [comment]
@jdoliner Are there any docs for this? I don't even see it in the basic pipeline spec docs

**Comment by jdoliner** [comment]
Doesn't look like there are unfortunately, oops. Do you min adding them?

**Comment by suneeta-mall** [comment]
@jdoliner  @JoeyZwicker  I did add in this PR but still outstanding https://github.com/pachyderm/pachyderm/pull/3133

**Comment by JoeyZwicker** [comment]
Ah perfect. Thanks Suneeta. Sorry that PR slipped through the cracks. We're on it

**Pull request merged**
