### PR TITLE
First crack at 1.5 changelog

### PR DESCRIPTION
**Pull request by sjezewski**
Please add / update anything I've missed. I went through the list of closed issues / PRs to make this list.

### CODE REVIEW

**Comment by sjezewski** [comment]
Fixes #1870

**Comment by derekchiang** [comment]
Is this supposed to be a list of changes since 1.4?  If so I think we are missing a large number of items.  See the changelogs here: https://github.com/pachyderm/pachyderm/releases

I think maybe we should move the changelogs on the release page to this file, and then have the 1.5 changelog be the changes since 1.4.8.

**Comment by derekchiang** [comment]
^I can do that once we are close to cutting the release.

**Comment by sjezewski** [comment]
I think the 1.5 changelog should be all the changes since 1.4

I do think there is higher fidelity in what is reported under the /releases path, and I'd be ok w that level of detail. [Here's an example of another project that solely uses the /releases feature to report changes](https://github.com/grpc/grpc-go/releases/tag/v1.3.0)

I like that they have the PRs / issues linked right in there. That makes it easy for me to evaluate if a newer release contains a relevant feature/bugfix I'm looking for.

**Comment by sjezewski** [comment]
Ah, on second thought I see what you're getting at Derek. If we only report changes on /releases ... then I guess it's fair to have the 1.5.0 CL only be since 1.4.8

Though in that case ... we miss the 1.4->1.5 change summary.

Which ... makes me think I've re-derived the need for the changelog :-P

**Pull request merged**
