### PR TITLE
Don't allow slashses in repo names

### PR DESCRIPTION
**Pull request by mattnenterprise**
This should fix issue #137

### CODE REVIEW

**Comment by jdoliner** [comment]
Many thanks for the pull1 Everything looks correct here except I think we should enforce this in a different place. Reason being driver is an interface that may have more than one implementation in the future and we don't want to have to enforce this separately for each.

Instead could you put the check in `pfs.APIServer.CreateRepo`?

Also would you mind filling out our CLA? https://pachyderm.wufoo.com/forms/pachyderm-contributor-license-agreement/

**Comment by jdoliner** [comment]
Whoops, just noticed you've already signed the CLA, feel free to ignore that :)

**Comment by mattnenterprise** [comment]
I believe I have it in the correct place now.

**Comment by jdoliner** [comment]
Indeed, merging!

**Comment by mattnenterprise** [comment]
This looks like it hasn't been merged.

**Comment by jdoliner** [comment]
Err, sorry I clicked the wrong button there.

**Comment by jdoliner** [comment]
There we go :)

**Pull request merged**
