### PR TITLE
Go modules

### PR DESCRIPTION
**Pull request by kevindelgado**
Nice little 2 million line diff for you. CI passes, loadtest passes, not sure if there's any more testing we need to confirm this. I noticed a couple test make targets seem to be stale, but pretty sure those aren't related to the modules stuff (they seem to be failing on current master too).

While we had previously been vendoring the various packages under `src` separately (and I had alluded to mirroring this with modules), I don't think this is a great idea going forward. It seems multi-module, single repos are hard (https://github.com/golang/go/issues/27056) and not recommended (https://github.com/golang/go/wiki/Modules#faqs--multi-module-repositories), but open to digging further into figuring out how to do it if we have a compelling reason to do so.

### CODE REVIEW

**Comment by kevindelgado** [comment]
merged in master, not sure if it makes the diff any cleaner.

**Comment by jdoliner** [comment]
It looks like this deleted `TestLargeObjects`, was that intentional? Unfortunately I can't comment on the diff in the github view since it's too big to load, so this comes from pulling the branch and doing `git diff master`

**Comment by kevindelgado** [comment]
Yes, according to @ysimonson:
>older version of the minio client would make a multipart upload request, detect that it failed, and gracefully fallback to using the normal upload endpoint, even for large files.

We had to upgrade the minio client we are using, and it does not fallback to the normal endpoint for large files, it instead hits the "NotImplementedError" our s3-gateway api returns when a PUT request is made for multipart uploads. 

Basically what this means is that anyone using a newer version of the minio-client happens to have reduced functionality when hitting our s3-gateway (not that our functionality itself has changed), it just so happens that our test is now using this newer version.

**Comment by ysimonson** [comment]
Did we ever figure out the cause of k8s' client module serving different hashes to different people? With this change, that would now affect pachyderm as well.

**Comment by kevindelgado** [comment]
Hmm, I have not been thinking much about this issue. I did encounter a similar issue once through the course of doing this modules stuff though, but following the accepted approach of clearing the mod cache seemed to resolve it (even thought that did not resolve it in our case).

Is it insufficient to say that if we do run into it again we can take the same approach of not committing `go.sum`? It seems like root cause is from modules created pre 1.11.3 (https://github.com/golang/go/issues/29278) and I'm not sure there's anything we do until the modules we depend on move past that.

**Comment by kevindelgado** [comment]
Gonna wait to merge this until I get back from PTO a week from monday. Seems like an opportunity for Very Bad Things® to happen and break dev workflows and I'd rather be around help smooth stuff over.

**Comment by ysimonson** [comment]
Ah, that's good to know. I suppose we could not commit `go.sum`, but that would mean that builds are no longer guaranteed to be reproducible. It's not clear to me, though, how much of a problem that is in practice with version pinning in `go.mod`, or whether we even want reproducible builds for the parts of pachyderm that may be pulled in as a dependency.

**Comment by ysimonson** [comment]
I tried pulling pachyderm as a module in for a project via `go get github.com/pachyderm/pachyderm@go-modules`, and got an error:

```
# github.com/pachyderm/pachyderm/src/server/pkg/uuid
../../go/pkg/mod/github.com/pachyderm/pachyderm@v1.9.1-0.20190628002107-63bd36ea3162/src/server/pkg/uuid/uuid.go:17:13: assignment mismatch: 2 variables but uuid.NewV4 returns 1 values
# github.com/pachyderm/pachyderm/src/client/pkg/config
../../go/pkg/mod/github.com/pachyderm/pachyderm@v1.9.1-0.20190628002107-63bd36ea3162/src/client/pkg/config/config.go:74:14: assignment mismatch: 2 variables but uuid.NewV4 returns 1 values
FAIL	github.com/pachyderm/s3gateway [build failed]
```

**Comment by hartzell** [comment]
@kevindelgado -- this will fix #3826 when you merge it, right?

**Comment by ysimonson** [comment]
@hartzell yes, that's correct

**Comment by kevindelgado** [comment]
> I tried pulling pachyderm as a module in for a project via `go get github.com/pachyderm/pachyderm@go-modules`, and got an error:
> 
> ```
> # github.com/pachyderm/pachyderm/src/server/pkg/uuid
> ../../go/pkg/mod/github.com/pachyderm/pachyderm@v1.9.1-0.20190628002107-63bd36ea3162/src/server/pkg/uuid/uuid.go:17:13: assignment mismatch: 2 variables but uuid.NewV4 returns 1 values
> # github.com/pachyderm/pachyderm/src/client/pkg/config
> ../../go/pkg/mod/github.com/pachyderm/pachyderm@v1.9.1-0.20190628002107-63bd36ea3162/src/client/pkg/config/config.go:74:14: assignment mismatch: 2 variables but uuid.NewV4 returns 1 values
> FAIL	github.com/pachyderm/s3gateway [build failed]
> ```

@ysimonson I am not able to reproduce this. Do you see this immediately when you run the `go get` command, or does that succeed and this error only arise later when your trying to build the project that imports `pachyderm/pachyderm` module?

**Comment by ysimonson** [comment]
@kevindelgado when building a project that pulls pachyderm in

**Comment by kevindelgado** [comment]
ok @ysimonson can you try again, I upgraded the uuid package.

**Comment by ysimonson** [comment]
That did it!

**Comment by ysimonson** [comment]
Actually, quick question before you merge. Are you definitely pulling in the latest from [go.uuid](https://github.com/satori/go.uuid)? Because it seems like the latest version of that lib has function signatures matching what's on master, rather than here. (e.g. `NewV4` is supposed to potentially return an error.)

**Comment by kevindelgado** [comment]
@ysimonson it's pulling in the latest release of go.uuid (v1.2.0) (https://github.com/satori/go.uuid/releases)  rather than the latest revision. (though you are correct that it appears like migrating to v1.2.0 is a downgrade)

This seems to be what's retrieved by `go get github.com/satori/go.uuid` by default (and at `@latest`), and I think it would be a pain to force users to manually update their versions of `uuid` in their own projects because we want to use a version newer than what the package is technically considering it's latest stable. 

Does that makes sense? It seems to me that the onus is on the owner of the uuid repo to cut a new release for the newer interface if that version is to play nicely with go modules, but I could me misunderstanding the situation.

**Comment by kevindelgado** [comment]
see https://github.com/satori/go.uuid/issues/90

**Comment by kevindelgado** [comment]
seems like the long term solution is to drop satori/uuid in favor of https://github.com/gofrs/uuid

**Pull request merged**
