### PR TITLE
Fix a bug where PPS thinks that a pipeline is running when it isn't

### LINKED ISSUE #549: Pipelines stuck in restarting on cluster restart
Steps to reproduce:
Create a pipeline in a locally deployed cluster
Destroy and recreate the cluster.
Pipelines should be stuck in `restarting`

### PR DESCRIPTION
**Pull request by derekchiang**
Fix #549

### CODE REVIEW

**Comment by jdoliner** [comment]
3ub75f

**Comment by derekchiang** [comment]
@jdoliner added some code to fix a bug where if `DeleteShard` comes in while a pipeline is being restarted, the pipeline ends up getting restarted anyways when it shouldn't.  Another LGTM?

**Comment by jdoliner** [comment]
Still lgtm, does it need a new meme?

**Comment by derekchiang** [comment]
nah one merge one meme

**Pull request merged**
