### PR TITLE
Expose advanced configuration for amazon client

### PR DESCRIPTION
**Pull request by brycemcanally**
This PR exposes some advanced configuration (retries, timeout, upload acl) for the amazon client. This advanced configuration is exposed as additional flags during the deployment process.

### CODE REVIEW

**Comment by pappasilenus** [comment]
@brycemcanally This didn't seem to work properly when applied as an upgrade to a cluster from 1.9.0.  Here are the steps I followed

1. deploy a 1.9.0 cluster against a swiftstack node with acls turned off
2. create a simple dag: opencv and object-recognition from examples
3. undeploy 1.9.0
4. create a manifest using this executable using the same authentication info, with a slightly different endpoint to allow the use of a non-ssl cluster with the amazon driver, along with `--upload-acl "public-read-write" ` (This seems to be the value that would work.)
5. deploy the manifest created
6. pachyderm starts up, but does not restore the old pipelines.  There are messages in the pachd logs, which are attached, along with the script I used to deploy.

[pachd.log](https://github.com/pachyderm/pachyderm/files/3638137/pachd.log)

[testing.txt](https://github.com/pachyderm/pachyderm/files/3638142/testing.txt)

**Comment by brycemcanally** [comment]
@pappasilenus I have tested this end to end (starting with a cluster with state created with the minio client and ending with a cluster with the correct state and the amazon client deployed and working). There are a few things that need to be changed to make this work. To start off, the upload acl value we should be using is `private` which is the default value for the upload acl (this is effectively making it a no-op). Next, the way we will need to handle the transition is through extract/restore. The reason you are seeing the object not found errors is because the amazon client reverses the object path, so it is looking for the reverse of the path uploaded by the minio client. Extract/restore gets us around this by reading with the minio client and re-uploading with the amazon client. Also, if the SwiftStack deployment has https enabled, then the endpoint we use should also be https (rather than http in the test). Our SwiftStack deployment does not have https enabled, so this is correct for our testing, but it should be https for users/customers who have https enabled. Something to note is that I was seeing the xml validation issue when reading with the minio client. This went away when I migrated to the amazon client. Go ahead and confirm this works for yourself, then I will merge this in.

**Comment by JoeyZwicker** [comment]
Just to make sure I'm fully following, users need to extract everything with 1.9.0 and then restore into 1.9.5 to switch clients here? @jdoliner Just want to confirm that that'll work with the new extract/restore changes with the salt, etc or is that issue linked to 1.9.0?

**Comment by jdoliner** [comment]
This shouldn't require extract / restore for 1.9.0 releases.

@brycemcanally could we perhaps include a fix for #4117 in this? I think it's as simple as adding one more parameter that can be configured.

**Comment by brycemcanally** [comment]
@jdoliner Yeah, that would be pretty simple. My only concern in general is that deployment is becoming a messy process since all of these things have to be configured through command flags. I still want us to move to a template based deployment so this stuff will be easier to work with, but I understand that it is not super high priority. I can add both a `PartSize` and `MaxUploadParts` to address #4117 . Do you prefer one or both?

**Comment by jdoliner** [comment]
I think you might as well just add both, I agree that configuration is becoming a mess and a template would make things nicer, but yeah, it just hasn't been a pressing problem yet.

**Comment by pappasilenus** [comment]
@jdoliner @brycemcanally @JoeyZwicker   I have confirmed that files are also inaccessible after an in-place upgrade. My impression that they were was because list-repo works, correctly showing file sizes:
```
$ pachctl  list repo
NAME     CREATED        SIZE (MASTER) 
detect   22 minutes ago 5.469MiB      
model    22 minutes ago 27.83MiB      
training 23 minutes ago 27.83MiB      
montage  31 minutes ago 2.662MiB      
edges    32 minutes ago 294.7KiB      
images   32 minutes ago 1.795MiB      
```

**Comment by pappasilenus** [comment]
@jdoliner @JoeyZwicker  Moving from minio -> S3 driver on SwiftStack without acls enabled  without having to do a migration works like a charm.  Here's the rough process:

```
#create the p7m cluster with a  minio manifest
${PACHCTL_1_9_0}  deploy custom --persistent-disk aws --object-store s3 foobar ${STORAGE_SIZE}  ${BUCKET_NAME} ${ACCESS_KEY} ${SECRET_KEY} ${ENDPOINT} --dynamic-etcd-nodes=1 --isS3V2 --dry-run > $MINIO_MANIFEST

kubectl apply -f $MINIO_MANIFEST

make opencv
make object-detection

${PACHCTL_1_9_0} undeploy

${PACHCTL_1_9_5_FIX}  deploy custom --persistent-disk aws --object-store s3 foobar ${STORAGE_SIZE}  ${BUCKET_NAME} ${ACCESS_KEY} ${SECRET_KEY} ${UPGRADE_ENDPOINT} --dynamic-etcd-nodes=1 --upload-acl "private" --reverse false --dry-run > $UPGRADE_MANIFEST

kubectl apply -f $UPGRADE_MANIFEST

${PACHCTL_1_9_5_FIX} put file images@master someimagefiles

```

**Pull request merged**
