### PR TITLE
fix(docs): update azure deployment documententation

### PR DESCRIPTION
**Pull request by jpoon**
* Update Azure documentation to deploy pachyderm with `--dynamic-etcd-nodes`. As AKS k8s deployments includes StorageClasses by default, this works right out of the box.  
* For users that continue to wish to use the `--static-etcd-nodes` they can use the `az disk create` CLI command (https://docs.microsoft.com/en-us/cli/azure/disk?view=azure-cli-latest#az_disk_create) to create a block volume. 
* Fixes: https://github.com/pachyderm/pachyderm/issues/2254 and https://github.com/pachyderm/pachyderm/issues/2136

### CODE REVIEW

**Comment by jpoon** [comment]
@dwhitena @jdoliner are those test failures my doing?

**Comment by JoeyZwicker** [comment]
@jpoon Nope those aren't you. Our CI just needs internal creds so it'll fail for external contributors. @dwhitena Docs are your domain, can you review and merge?

**Comment by dwhitena** [comment]
Ah this is a great simplification! Love it. I will open a corresponding PR to run CI @JoeyZwicker.

**Comment by JoeyZwicker** [comment]
#2500 passed CI. Merging

**Pull request merged**
