### PR TITLE
Fix links to examples in documentation

### PR DESCRIPTION
**Pull request by svanharmelen**

### CODE REVIEW

**Comment by JoeyZwicker** [comment]
Thanks for catching this @svanharmelen! We'll dig into why CI is failing (it shouldn't be since this is a simple docs change) and then get this merged in. In the meantime, can you sign our [CLA](https://pachyderm.wufoo.com/forms/pachyderm-contributor-license-agreement/)?

**Comment by JoeyZwicker** [comment]
@svanharmelen CI is all ready to go whenever you have a chance to sign our CLA. :)

**Comment by svanharmelen** [comment]
Thanks @JoeyZwicker! Just signed the CLA 👍

**Comment by JoeyZwicker** [comment]
Done! Thanks again! Feel free to join our [Slack Channel](slack.pachyderm.io). We'd love to learn more about how you found Pachyderm, what use case you have in mind, and we'll of course be there to help if you get stuck on anything else

**Pull request merged**
