### PR TITLE
size can be 0 for Reader() by default, handle it.

### LINKED ISSUE #1385: Minio backend bug in getting files
# Behavior

Pachyderm backed by Minio in Google Cloud (and possibly elsewhere) is able to:

- create repositories
- put data into repositories

However, when you try to get versioned data out of PFS, the files always return blank, even though you can see that the file content was written to the object store (either via the Minio browser or via `pachctl list-file` and `pachctl list-repo`).

# To Recreate

## Deploy Minio

- spin up a VM on GCE and deploy Minio via:

```
docker run -p 9000:9000 minio/minio server /export
```

- get the Minio creds via

```
docker logs <container id>
```

## Deploy k8s

- set up the environment:

```
CLUSTER_NAME=pach-cluster
GCP_ZONE=us-west1-a
gcloud config set compute/zone ${GCP_ZONE}
gcloud config set container/cluster ${CLUSTER_NAME}
```

- create the k8s cluster

```
gcloud container clusters create ${CLUSTER_NAME} --scopes storage-rw
```

- update kubectl 

```
gcloud container clusters get-credentials ${CLUSTER_NAME}
```

## Deploy Pachyderm backed by Minio

- create a persistent disk:

```
STORAGE_NAME=pach-minio-disk
STORAGE_SIZE="10"
gcloud compute disks create --size=${STORAGE_SIZE}GB ${STORAGE_NAME}
```

- deploy pachyderm backed by minio (using pachctl 1.3.12)

```
pachctl deploy custom --persistent-disk google --object-store s3 ${STORAGE_NAME} ${STORAGE_SIZE} <minio bucket> <minio id> <minio secret> <public ip of minio VM>:9000
```

- once pachyderm is up, port-forward

```
pachctl port-forward &
```

## Put some data in PFS and try to get it back

1. create a repo in Pachyderm

```
➔ pachctl create-repo testminio
➔ pachctl list-repo
NAME                CREATED             SIZE                
testminio           11 seconds ago      0 B
```

2. push data to the repo (in this case just the pachyderm README.md)

```
➔ pachctl put-file testminio master blah -c -f README.md 
➔ pachctl list-repo
NAME                CREATED              SIZE                
testminio           About a minute ago   9.92 KiB
```

3. list the file to make sure it was written with non-zero size

```
➔ pachctl list-file testminio master 
NAME                TYPE                MODIFIED            LAST_COMMIT_MODIFIED   SIZE                
/blah               file                45 seconds ago      master/0               4.96 KiB
```

4. examine the file in the Minio Browser to see it has content

image

5. try to get the file

```
➔ pachctl get-file testminio master /blah
➔ 
```

(this returns without error much return empty, where we would expect to get the content)

6. you can also use `pachctl mount` to mount PFS locally and browse the fs.  This also show blank files, although we know the content was written to the object store.

# Thoughts

- For some reason everything returned when getting files is empty.  Maybe a bug in the Minio client get functionality?

- The Minio client works at least for putting files.  Is there something different about getting files?

### PR DESCRIPTION
**Pull request by harshavardhana**
In minioClient pfs driver implementation Reader()
did not handle the case of reading the entire file
i.e when size was provided as '0'.

This is the default behavior for someone reading a file

```
pachctl get-file testminio master /blah
```

Re-factor the code a bit to address the cases of offset and
size independently without using the SectionReader() since
it is not guaranteed that size is always > 0.

Fixes #1385

### CODE REVIEW

**Comment by harshavardhana** [comment]
// cc @dwhitena

**Comment by dwhitena** [comment]
I can confirm that this works!! Thanks @harshavardhana 

```
➔ 
➔ pachctl create-repo testminio
➔ pachctl list-repo
NAME                CREATED             SIZE                
testminio           9 seconds ago       0 B                 
➔ pachctl put-file testminio master blah -c -f README.md 
➔ pachctl list-repo
NAME                CREATED             SIZE                
testminio           30 seconds ago      9.92 KiB            
➔ pachctl get-file testminio master /blah
<img src='doc/pachyderm_factory_gh.png' height='225' title='Pachyderm'> 

[![GitHub release](https://img.shields.io/github/release/pachyderm/pachyderm.svg?style=flat-square)](https://github.com/pachyderm/pachyderm/releases)
[![GitHub license](https://img.shields.io/badge/license-apache-blue.svg)](https://github.com/pachyderm/pachyderm/blob/master/LICENSE)
[![GoDoc](https://godoc.org/github.com/pachyderm/pachyderm?status.svg)](https://godoc.org/github.com/pachyderm/pachyderm/src/client)
[![Slack Status](http://slack.pachyderm.io/badge.svg)](http://slack.pachyderm.io)

# Pachyderm: A Containerized, Version-Controlled Data Lake

Pachyderm is:

...
```

**Comment by jdoliner** [comment]
@dwhitena does this look good for merge to you?

**Comment by dwhitena** [comment]
@jdoliner yes LGTM!

**Comment by harshavardhana** [comment]
> @jdoliner yes LGTM!

Is there a way to test with offsets and specific length with 

```
pachctl get-file testminio master /blah
``` 

?? - once this is done it would cover all the cases of reading an object. 

// cc @dwhitena @jdoliner

**Comment by dwhitena** [comment]
@jdoliner do you know about @harshavardhana's question above?

**Comment by jdoliner** [comment]
@harshavardhana there's not, but you can with the golang api

**Comment by harshavardhana** [comment]
Tested with 

```
package main

import (
        "bytes"
        "log"

        "github.com/pachyderm/pachyderm/src/client"
)

func main() {
        // Connect to Pachyderm.                                                                                                                                                                                                                                                                                                                                                             
        c, err := client.NewFromAddress("**REDACTED**:30650")
        if err != nil {
                log.Fatal(err)
        }

        var buffer bytes.Buffer

        log.Println("Testing reading all file")
        if err = c.GetFile("testminio", "master", "/blah", 0, 0, "", false, nil, &buffer); err != nil {
                log.Fatal(err)
        }
        if buffer.Len() == 0 {
                log.Fatalf("Expected all the data, nothing sent")
        }
        log.Println("Success.")
        origDataLen := buffer.Len()
        buffer.Reset()

        log.Println("Testing length > 0 and offset == 0")
        if err = c.GetFile("testminio", "master", "/blah", 0, 100, "", false, nil, &buffer); err != nil {
                log.Fatal(err)
        }
        if buffer.Len() != 100 {
                log.Fatalf("Expected buffer value 100, got %d\n", buffer.Len())
        }
        log.Println("Success.")
        buffer.Reset()

        log.Println("Testing length as zero and offset > 0")
        if err = c.GetFile("testminio", "master", "/blah", 100, 0, "", false, nil, &buffer); err != nil {
                log.Fatal(err)
        }

        if buffer.Len() != origDataLen-100 {
                log.Fatalf("Expected buffer value %d, got %d\n", origDataLen-100, buffer.Len())
        }
        log.Println("Success.")
        buffer.Reset()

        log.Println("Testing length > 0 and offset > 0")
        if err = c.GetFile("testminio", "master", "/blah", 100, 1, "", false, nil, &buffer); err != nil {
                log.Fatal(err)
        }
        if buffer.Len() != 1 {
                log.Fatalf("Expected buffer value 1, got %d\n", buffer.Len())
        }
        log.Println("Success.")
        buffer.Reset()
}
```

Works for all offsets and length combination.

**Comment by jdoliner** [comment]
Groovy.

**Pull request merged**
