### PR TITLE
Protobuf cleanup

### PR DESCRIPTION
**Pull request by roylee17**
The PR intends to reduce protobuf related dependencies to gogo protobuf, which has been used/imported anyway.

### CODE REVIEW

**Comment by jdoliner** [comment]
This seems like some very valuable cleanup. Many thanks.
Looks like CI failed but I think it might be transient, I restarted it.
This seems to update us to the latest version of grpc, does everything seem to function with this version? If so that'd be a huge piece of technical debt payed down!

**Comment by sjezewski** [comment]
Oh, very cool. I like the meta data for proto field names, which eliminates the need for our one-off tool to fix this. So, this PR should also delete `https://github.com/pachyderm/pachyderm/tree/master/src/server/cmd/protofix`

**Comment by roylee17** [comment]
Currently, some external packages altogether form a "ecosystem" on its own. It's rather difficult to change/update/remove any of them without hacking the rest. And when the dependencies involve protobuf, it get much more complicated.

This PR is a breakdown of a much larger WIP branch, which removes more external dependencies.
(So itself is not vey clean for merge yet, you can tell from the lasts two dumb commits)

But before I "clean up the cleanup", I'd like to know the team is up to it. Glad the team is positive about it :-)

If we don't have a strong affinity to stick with specific package or implementation, we can take a further step to use independent alternative packages, or just port it over. (proto/stream, rpclog, version, etc)

I can keep update the mergable changes on the branch tracked by this PR, so we can keep review it and feedback until we feel comfortable with all the changes.

In the meantime, don't worry about any conflict if you're actively working on large change set  or refactoring. I can keep rebasing accordingly along the way.

p.s. The CI failed due to some changes in the _test.go were left out in the last moment re-grouping before PR. I'll fix it in the next update.

**Comment by derekchiang** [comment]
This PR is extremely helpful.  We have been trying to migrate to grpc v4 for a while but the deps are just too hairy to tackle, but looks like you've mostly got it working.  Would really love to see this merged asap.

**Comment by jdoliner** [comment]
Looks like there's a small issue that's keeping this from passing in CI. There's a rethink query that is trying to access a field called `Size` on a document but the document's field is called `SizeBytes`. It looks like you went through and just changed every instance of `Size` to `SizeBytes` which I approve of since it unifies things. I think all you need to do is go through `src/server/pfs/db/driver.go` and change instances of `Size` to `SizeBytes` and CI will pass.

**Comment by derekchiang** [comment]
@roylee17 I fixed the issue that JD mentioned [here](https://github.com/pachyderm/pachyderm/pull/1248/commits/9f1e70a8dcd72041221f7ab6c4e8563190893e2d), so feel free to cherry-pick it.  At the same time, I also discovered another issue: pipeline specs are not being parsed correctly.  So if you run this code and try to create a pipeline: ` pachctl create-pipeline -f doc/examples/fruit_stand/pipeline.json`, you are going to get errors similar to this one:
```
unknown value "CONSTANT" for enum pps.ParallelismSpec_Strategy
```

So for some reason, the JSON string "CONSTANT" is not being parsed correctly into the enum `pps.ParallelismSpec_Strategy`, even though the value `CONSTANT` is in fact defined in the enum.  The same problem applies to all other enum types we have such as `pps.Method`.  I'm not really sure what's causing this issue.  Probably something changed in the new version of protobuf?

**Comment by roylee17** [comment]
@derekchiang didn't see your comment earlier. I just squashed similar change, and rebase to master, so the problem probably still exists. Ignore this push. I'll try to reproduce it and get back.

Keep commenting any other issue/difference found between the changes, thx.

**Comment by roylee17** [comment]
@derekchiang the last two commits should address the issues found. I went through the fruit_stand tutorial.

**Comment by roylee17** [comment]
`make example-tests` passes.

Not sure it's my environment or something, I still haven't got `make test-fuse test-local` working locally. `make integration-tests` can't finishes as my minikube might be too mini...
Might have to trouble travis  a few more times before I figure out what's missing on my set up.

**Comment by jdoliner** [comment]
@roylee17 our tests can unfortunately be very sensitive to different environments. I often have to iterate on CI to get stuff to pass.

**Comment by sjezewski** [comment]
Hey @roylee17 -- there are a lot of good changes in here and we really need the GRPC upgrade (we ran into another issue this week that we think is related). So I'm going to run w this PR so we can get this work merged in. I'll pull from your remote and setup a new branch on this repo and go from there. 

I'll ping you as I have any questions. Thanks!

**Pull request merged**
