### PR TITLE
Update OpenShift docs for create a pipeline section

### PR DESCRIPTION
**Pull request by nak3**
docs: Update OpenShift docs for creating a pipeline

To create a pipeline on OpenShift, users need some more additional
steps. This patch describes how to configure it.

### CODE REVIEW

**Comment by JoeyZwicker** [comment]
rerunning CI to make sure it passes and then we can merge this in -- sorry it slipped through the cracks.

**Comment by sudhirpandey** [comment]
Instead of doing all the fixes for service account pachyderm to be able to run containers in pachyderm, I have tried to have this instead `oadm policy add-scc-to-user privileged system:serviceaccount:pachyderm:default` , This is default sa user of the rc  so we dont have to fix all  permission issue  (ie oc patch with service account) repeatedly when pipeline is updated . Thus the generated rc from pipeline works ootb.

**Comment by nak3** [comment]
In my opinion, the rc generated by pachyderm should have pachyderm service account.

I wanted to avoid adding privileged to default (entirely in pachyderm project), but yeah `oadm policy add-scc-to-user privileged system:serviceaccount:pachyderm:default` is more useful atm (since rc doesn't have pachyderm by default).

**Comment by JoeyZwicker** [comment]
@dwhitena is this documented in our openshift docs?

**Pull request merged**
