### PR TITLE
Opencv fixes

### PR DESCRIPTION
**Pull request by jdoliner**
Changes I made for the opencv talk.
Mostly just touches examples/opencv/...
But also one change to the core server.

### CODE REVIEW

**Comment by jdoliner** [comment]
@msteffen whenever you have a chance.

**Comment by msteffen** [comment]
lion-baby

**Comment by msteffen** [comment]
For what it's worth, I think in a perfect world the "Don't list archived / cancelled branches" change would be a separate branch, so that it could be reviewed separately. But it's a very small change.

**Comment by jdoliner** [comment]
Yeah, 100% agree. These were all made in a panic as I was trying to get the demo working in time for the talk. I considered splitting them up but it seemed small enough that it wasn't really worth it.

**Pull request merged**
