### PR TITLE
Report create-pipeline progress

### PR DESCRIPTION
**Pull request by derekchiang**

### CODE REVIEW

**Comment by jdoliner** [comment]
I don't really see the point of this. When `create-pipeline` returns with a 0 exit code most users should be able to infer that the pipeline was successfully created. Also if this was something we wanted to do why would we only do it for `create-pipeline` and not for other commands?

**Comment by derekchiang** [comment]
When I'm creating multiple pipelines together, sometimes it takes a while, and there is no way for me to tell if it's making progress or if something has gone wrong.  Some other commands can definitely benefit from progress reporting as well though.

**Comment by jdoliner** [comment]
When does create-pipeline take a while? I haven't seen that and looking at the code it looks like all it does is create a repo and then insert a row into the database which should be really quick. I also don't understand which errors can occur that won't result in the command returning really quickly with that error. Are there errors that cause `create-pipeline` to hang for extend periods?

Consistency of the output of pachctl seems really important to me because people are likely going to write scripts using it. Right now we have the simple rule that `create-*` returns an ID if one is generated, otherwise it returns nothing. If we're going to do something like this then I think it's important we do it consistently across all of the commands but I also don't think we want every command to return: "successfully did the thing you told me to do" do we?

**Comment by derekchiang** [comment]
That makes sense.  In my case I'm creating three pipelines which takes around 5-10s.  But yeah I'm guessing that's not necessarily long enough to justify progress reporting.

**Pull request closed without merging**
