### PR TITLE
WIP: Autoformat docs

### PR DESCRIPTION
**Pull request by jrockway**
This PR adds a Prettier configuration to allow auto-formatting of docs, either in your editor or with `make format-docs`.

Marked as a work in progress because I can't get the docs to serve locally yet, to see if the formatting breaks any cosmetics.

### CODE REVIEW

**Comment by jrockway** [comment]
Indeed, the auto-formatting breaks things; at least "!!! tip" sections are broken.  Will investigate.

**Comment by svekars** [comment]
@jrockway we do use quite a lot of markdown extensions on the official docs website which formatting will likely be broken by this change. Here is the full list of extensions: https://github.com/pachyderm/pachyderm/blob/master/doc/mkdocs-master.yml#L63.

**Comment by jrockway** [comment]
I think my plan is to go through and add `<!-- prettier ignore -->` directives in the affected areas.  It's a known issue: https://github.com/prettier/prettier/issues/3362

**Comment by svekars** [comment]
Sounds good. Just need to make sure we add all needed exceptions.

**Pull request closed without merging**
