### PR TITLE
Replace local file reference with reference to raw git file

### PR DESCRIPTION
**Pull request by nysthee**

### CODE REVIEW

**Comment by JoeyZwicker** [comment]
Thanks @nysthee! @dwhitena will review this (it's such a simple change so that'll only take 10 seconds) and get it merged in. 

Can you sign our [CLA](https://pachyderm.wufoo.com/forms/pachyderm-contributor-license-agreement/)?

**Comment by nysthee** [comment]
✅

**Comment by nysthee** [comment]
Signed!

**Comment by JoeyZwicker** [comment]
Thanks, we'll get this reviewed and merged in shortly.

**Comment by dwhitena** [comment]
CI is failing b/c of an intermittent problem I think, but merging b/c this a docs change. Thanks again!

**Pull request merged**
