### PR TITLE
feat: Generate JSON schema for PPS proto.

### PR DESCRIPTION
**Pull request by loganripplinger**
This produces a JSON schema for all protos. This gives you beautiful autocomplete in your IDE of choice while writing a pipeline spec. 🎉 (After this is merged, dump `"$schema":"https://raw.githubusercontent.com/pachyderm/pachyderm/master/jsonschema/CreatePipelineRequest.schema.json"` into your PipelineSpec and Visual Studio will autocomplete/validate the spec!  For users of other editors, `brew install vscode-langservers-extracted`.  In emacs, M-x eglot on a JSON file Just Works after this.)

There is some follow-up work to get maximum value out of this in https://pachyderm.atlassian.net/browse/CORE-1939.

### CODE REVIEW

**Comment by jrockway** [comment]
I modified this to generate a schema for every message for the time being.  That's because these protos are used as JSON in other places, like `pachctl auth set-config` takes a `auth.OIDCConfig` message.  Eventually we will want to emit `$schema` tags on these objects, so people can enjoyably edit them!

**Review by jrockway — APPROVED** [review]

**Review by bbonenfant — APPROVED** [review]
Integrations team has no objections to these changes. One thing I noticed is that all of the enums are bundled into the individual jsonschema files that use them. I don't know if this is intended or not, but it seems worth mentioning.

**Comment by jrockway** [comment]
Yeah, it seems the way it generates schemas is so that there are no external references; if you're making a CreatePipelineRequest, you don't need anything other than CreatePipelineRequest.schema.json.  This seems like a good idea to me, because the code generation doesn't have to be aware of where the rest of the schemas are located.

**Comment by robert-uhl** [comment]
> In emacs, M-x eglot on a JSON file Just Works after this.

Note for future folks: I did have to run `snap install vscode-json-languageserver` as well.

**Pull request merged**
