### PR TITLE
Add a -f flag to put-file; fix #534

### LINKED ISSUE #534: put-file should accept a -f flag that specifies a file
Currently the canonical way to put a file is something like this:

```
cat data.txt | pachctl put-file repo master data.txt
```

Note how you have to specify `data.txt` twice.  Ideally you should be able to do this:

```
pachctl put-file repo master -f data.txt
```

### PR DESCRIPTION
**Pull request by derekchiang**
So now you can:

```
$ pachctl put-file data master -f file.txt
$ pachctl put-file data master another-name.txt -f file.txt
```

### CODE REVIEW

**Comment by jdoliner** [comment]
Does `-f -` read from stdin?

**Comment by derekchiang** [comment]
@jdoliner no.  Should it?

To be clear, you can still read from stdin the exact same way as before.  You just don't provide the `-f` flag.

**Comment by sjezewski** [comment]
LGTM

image

**Comment by jdoliner** [comment]
I'd kind of expect it to, because `create-pipeline` supports that. Although you'll need to error if they try to do `-f -` without providing a file name.

**Pull request merged**
