### PR TITLE
Update the github issue template to be goal-oriented

### PR DESCRIPTION
**Pull request by gabrielgrant**
The current template for feature requests focuses on the specific proposed solution, rather than the user need. It feels like we should be encouraging the opposite (and I usually find myself editing the template to do so when creating new issues)

### CODE REVIEW

**Comment by JoeyZwicker** [comment]
LGTM.

**Comment by jdoliner** [comment]
I'm not totally sure this is an improvement. "What is the ask?" and "What is the goal / desired outcome?" do seem a little redundant, I think people have been interpreting them as "What is your situation / use case?" and "How do you imagine this being solved?" which is getting us the information we want. I worry that "What is the goal / desired outcome?" will just get us short answers like "I want to run my pipeline on historical data." without pushing people to tell us more about their use case / situation from which we normally discover that they're doing something else wrong with the system and won't need the behavior they think they want if they use the system as intended. That was the main purpose of this template initially.

**Comment by jdoliner** [comment]
Another worry I have is that by asking: "**What is your proposal for a feature to solve this?**" it makes it seem like we're looking for people to have a thought out implementation for the feature, some people will have this but we probably don't want people to feel like that's a requirement for opening an issue.

**Comment by jdoliner** [comment]
Changed this ever so slightly, ordering and specifying that feature recommendation is optional. Not sure if it really improves it much, I probably should have just merged this initially.

**Pull request merged**
