### PR TITLE
Fix typos improve readability in beginner_tutorial [ci skip]

### PR DESCRIPTION
**Pull request by discdiver**
Travis-CI is running and failing despite [ci-skip] in commit message. Message below. 

Clearly not relevant for a doc contribution. Is there something else I should be doing to get Travis to pass?

```
(2) Please paste the token you receive from GitHub here:
Retrieving Pachyderm token...
error activating Pachyderm auth: Pachyderm Enterprise is not active in this cluster, and the Pachyderm auth API is an Enterprise-level feature
make: *** [test-vault] Error 1
The command "etc/testing/travis.sh" exited with 2.

```

### CODE REVIEW

**Comment by gabrielgrant** [comment]
@discdiver thanks for the fixes! 

Sorry about the benign Travis failures: the CI process uses some private secrets, which has the annoying side effect that it always fails for PRs from people outside the pachyderm github org (to avoid those secrets from being exposed). Would you mind filling out the CLA: https://pachyderm.wufoo.com/forms/pachyderm-contributor-license-agreement/
Then someone on the team can get this through CI and merged in (@JoeyZwicker  ?)

Thanks again!

**Comment by discdiver** [comment]
Thanks @gabrielgrant. No sweat. I filled out the CLA a day or two ago. Please let me know if it didn't come through and I should fill it out again.

**Comment by JoeyZwicker** [comment]
@Nick-Harvey or I will review/merge this shortly

**Comment by Nick-Harvey** [comment]
Given the work Matt did with https://github.com/pachyderm/pachyderm/issues/3390, I went ahead and just applied these manually to avoid merge conflicts. **@discdiver gets all the credit for these changes**, thanks for the changes 🥇

**Pull request closed without merging**
