### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by kaktus42**
also filled the CLA

### CODE REVIEW

**Comment by JoeyZwicker** [comment]
@dwhitena feel free to merge after CI passes

**Comment by jdoliner** [comment]
This needs `make doc` run for the changes to actually propagate to our online docs and not just `pachctl`.

**Comment by kaktus42** [comment]
no merge?

**Comment by jdoliner** [comment]
We're happy to merge after `make doc` is run, we could even do that step for you it's just a bit of a pain to commit it back to this PR since it's based off of your personal branch, so I'd have to create a separate PR.

**Comment by kaktus42** [comment]
ah. now I understand.
I didn't get that I have to run the make doc ;)
Will do.

2018-05-09 18:47 GMT+02:00 Joe Doliner <notifications@github.com>:

**Comment by jdoliner** [comment]
Merging this, docs will propagate in the next release. Sorry for letting this sit so long @kaktus42

**Pull request merged**
