### PR TITLE
Docs improvements

### PR DESCRIPTION
**Pull request by ssaamm**

### CODE REVIEW

**Comment by JoeyZwicker** [comment]
Thanks @ssaamm! Can you sign our [CLA](https://pachyderm.wufoo.com/forms/m1kv71oe04eawdn/) and we'll get this merged?

**Comment by ssaamm** [comment]
My bad. Signed!

**Comment by JoeyZwicker** [comment]
@dwhitena Status here?

**Comment by dwhitena** [comment]
@JoeyZwicker I think we need to reformat any relevant content here into the new troubleshooting format.  The old troubleshooting docs were re-arranged and updated around the time this was submitted.

**Comment by dwhitena** [comment]
Some relevant bits pulled in, conflicts resolved, format updated, and additional typos corrected in: https://github.com/pachyderm/pachyderm/pull/2504

**Pull request closed without merging**
