### PR TITLE
Storage Layer Overview

### PR DESCRIPTION
**Pull request by brycemcanally**
This PR is intended for iterating on the overview of the new storage layer.

### CODE REVIEW

**Comment by jdoliner** [comment]
I think this overview assumes why too much knowledge on the part of the audience, it's more of an overview of the changes being to the existing storage layer rather than an overview of the storage layer as a whole when I think the latter is going to be a lot more useful. I don't think there's anyone at the company who's going to be able to understand the storage layer from this, except for me, because I understand the current storage layer, but I shouldn't be the target audience for this because I already mostly understand the changes being made. I think it's probably best to assume the audience basically knows nothing except for what filesystems in general do.

I'd like to see this written with no references to the current storage layer and explaining from first principles what the goal of Pachyderm's storage layer is in general, why those goals are difficult, and how we accomplish, or will accomplish, them. This should ultimately be a document that we can publish publicly and a person who has no familiarity with Pachyderm, but does have some general understanding of filesystems, could understand the storage layer at a high level.

A few specific questions that need to be answered in this:

- What is the storage layer responsible for storing? This is the first most basic question, I would answer this as "large filesystem snapshots," but feel free to word it how you'd like.

- What interface does it need to expose to this filesystem? People can guess the basics here, but it's still worth going over stuff. This is where you'd talk about exposing stable hashes for files and directories and merging, but also just the basic stuff like getting file content and listing files. 

- Why is this hard? This is where you should start talking about performance, everything we're doing is pretty easy if you don't need to make it fast. I like talking about a strawman here: what if we just stored a tarball for each commit, dead simple implementation that could semantically satisfy all of our needs, but the performance would be completely untenable.

- What are the core algorithms we're using to implement this? This should be explained as close as possible to the point where you explain the problems they solve so readers have the context of why they're interesting. Things I'd expect to see in here: content addressing, this is the core algorithm that everything else is built on, assume readers have no idea what it is. Content chunking, makes content addressing much more effective, again assume readers have no idea how it works. Tree based merge and compaction, these probably are more generally understood, but still makes sense to explain them from a clean slate.

- What are the performance characteristics of the underlying medium? This has informed a lot of our decisions, and is largely unknown. Most people just assume that cost is determined by amount stored, but that's generally not true with hosted object stores.

- What actually gets stored on disk, why was tar chosen as the base format?

**Comment by brycemcanally** [comment]
I agree entirely about what needs to be covered in our documentation, but I think you are jumping the gun a little bit for this particular document. This document is not intended for diving too deep into the details, it is an overview which should contain information at a high level about the problems being addressed, architecture, and storage format. The part that is in the PR right now is just the problems being addressed portion. It is not intended to provide a deep dive into why the current storage layer has these problems or how the new storage layer is addressing them. The details will be addressed in separate documents for each of the components (I am thinking it makes sense to have a document for the chunk storage layer, file set layer and indexing, and merging and compaction). I think it would be overwhelming for non-technical folks to be dragged through the weeds when trying to get some understanding of why the new storage layer is better. If you really want me to lay it all out in the overview, I can do that, but I don't think that is how we want to present it particularly because I imagine there are a lot of non-technical folks who will not be interested in the details.

On a side note, something @nitinjainsj and I talked about is presenting the current storage layer to help elucidate the problems identified, but I feel like this could be kind of tricky because of how haphazard the overall design is. I'm not sure if it is going to make a ton of sense to try and collect and present that information.

**Comment by jdoliner** [comment]
The goals you describe are the goals I had in mind when writing the above feedback. This document as is doesn't succeed in any of the goals that you lay out. It doesn't contain high level information about the problems being addressed, it contains very low level implementation details about specific things being changed between the existing storage layer and the new layer, while failing to answer even the most basic questions about the storage layer such as what it's actually responsible for storing. I really don't know how you can consider that information too in the weeds for non-technical people while the subtleties of file hashes being different when they're created with a different sequence of operations (which is where the document starts) is supposedly high-level enough that non-technical people can get it. You're not even defining what file hashes are, which is something that non-technical people could actually get, and which would immensely help their understanding of what the storage layer does (I was thinking this information would be in the section where you talk about the interface it exposes.) You're diving straight into the weeds of a very particular problem that the existing storage layer has which the new one doesn't, it's exactly the type of detail that non-technical people, and most of the rest of the engineering team will not be interested in at all.

**Comment by brycemcanally** [comment]
> I really don't know how you can consider that information too in the weeds for non-technical people while the subtleties of file hashes being different when they're created with a different sequence of operations (which is where the document starts) is supposedly high-level enough that non-technical people can get it.

I think instead of non-technical people, I should have said people who do not have a strong engineering background (some data scientists for example). The assumption I have been making, which may be incorrect, is that the people reading this overview would be familiar with Pachyderm concepts (not the internals). The idea of file hashes is pretty basic in Pachyderm and giving some idea about why that is not computed based solely on the content is necessary to convey. All of these concepts should be familiar to a Pachyderm user (except maybe the mention of objects and how they correspond to individual insertions, so it might make sense to explain that a bit differently).

I think it might be kind of tricky to convey the issues being addressed without some in the weeds stuff, but I tried to keep it minimal. I'll see if I can make some changes to move away from the more precise explanations and instead describe the issues in a way that does not feel like stepping halfway into the details. Also, I can add a bit at the beginning that leads into it a bit more comfortably (I do agree that it is a bit abrupt to just be like here are some problems).

**Comment by brycemcanally** [comment]
Storage layer overview is here #4363

**Pull request closed without merging**
