### PR TITLE
Doc update: add AWS one-shot script removal instructions

### LINKED ISSUE #2638: Instructions how to delete cluster created with AWS one-shot deploy script
http://pachyderm.readthedocs.io/en/latest/deployment/amazon_web_services.html

There are no instructions how to delete this test cluster. I have very basic familiarity with kops+pachyderm+kubernetes etc, so I started the one-shot deploy cluster, but now I need it gone, and I'm left guessing that hopefully there won't by any infrastructure left costing me money.

Perhaps expose this with a kops command?

### PR DESCRIPTION
**Pull request by dionjwa**
Fixes #2638

### CODE REVIEW

**Comment by dionjwa** [comment]
It's failing with this message:
```
go test -v ./src/server/auth/server -timeout 3600s
=== RUN   TestAdminRWO
--- FAIL: TestAdminRWO (0.00s)
panic: cannot get test enterprise token from s3: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors [recovered]
	panic: cannot get test enterprise token from s3: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

**Comment by dionjwa** [comment]
@jdoliner

**Comment by dwhitena** [comment]
Thank you very much @dionjwa. Have you signed the CLA? I'll kick off CI, which needs someone internal to Pachyderm to kick it off.

**Comment by dionjwa** [comment]
I just signed the CLA now.

**Comment by dwhitena** [comment]
Thanks! merging.

**Pull request merged**
