### PR TITLE
Adds support for pprof tracing.

### PR DESCRIPTION
**Pull request by jdoliner**
As part of this pr I also add `make manifest` and `make dev-manifest` targets because I needed to remake the manifests. I seem to remember us having those at one point but maybe they got removed or something.

### CODE REVIEW

**Comment by sjezewski** [comment]
Ah, I think those make tasks got removed when we automated the release process. In particular, I think I didn't want anyone 'foot-shooting' by regenerating the versioned manifest locally. But it makes sense why you'd want to have the dev version as a make task.

**Comment by sjezewski** [comment]
Reading through the changes it makes sense why you'd want to update the versioned manifest as well. However, if we merge this PR as-is, the versioned manifest thats available locally in the repo is different from the one available on the website. 

That means the behavior of `make launch` and the command `kubectl create -f https://pachyderm.io/manifest.json` will have different results.

To keep those in sync, we can run the release script again. But in this case, that's what I was hoping to avoid by exposing `make manifest`. (Running the release task will update the manifest as part of the task).

I think we should have two different versions of the stable manifest released. That seems like it'll lead to some confusion about which manifest is being used (esp when we're helping someone debug). Both versions will contain the same version strings for the images, so will be hard to distinguish.

I guess it depends on how we see this feature being used. 

Do we:

A) Assume they have to use `make dev-launch` to get pre-release features?

If so, I'd recommend removing the 'make manifest' task / undoing the changes to the versioned manifest

OR

B) Assume they'll only ever run `make launch` or `kubectl create -f https://pachyderm.io/manifest.json`

In which case, I would still remove the `make manifest` task, but run the release automation script (which itself should generate the versioned manifest)

----

Other than my nitpicking about versions, LGTM

**Comment by jdoliner** [comment]
I think your comments make sense, I'm just going to remove the make task and the new versioned manifest. It really doesn't make sense as is because the versioned manifest has port information for pprof but the 1.1 server doesn't expose it.

**Comment by jdoliner** [comment]
@sjezewski another look when you have a chance

**Comment by jdoliner** [comment]
Or I guess you already said LGTM excepting the version stuff which I removed so I can probably just merge this.

**Comment by sjezewski** [comment]
image

**Comment by jdoliner** [comment]
Perfect meme, did you make this for the PR or somehow find one this perfect?

**Comment by sjezewski** [comment]
Haha, I made it ;-)

I mostly use: https://imgflip.com/memetemplates

Pretty soon our code reviews will involve reviewing the memes!

**Pull request merged**
