### PR TITLE
Fixes a few things about the default pager.

### PR DESCRIPTION
**Pull request by jdoliner**

### CODE REVIEW

**Comment by JoeyZwicker** [comment]
I was actually going to ask about this. Should the pager be the default or should we default to what it was before (PAGER=cat I think is the envvar I use) and then just have this as an option people can activate if/when list job gets slow? 

It seems a little weird that list job is different than the other commands and I don't think we necessarily want to change all of those, right?

**Comment by Tryneus** [comment]
I think using a pager by default is the right thing to do - LGTM

**Comment by jdoliner** [comment]
I don't think it ever makes sense as an option, it's always implicitly an option since you can just add `| less` to the end of your command which is shorter than typing `--pager`. It makes a lot of sense for `list job` to be different than other commands because it generally has a lot of output and the most interesting output is generally at the top, which isn't true of all commands. We've had many requests from users to implement some sort of a pager for `list job` so we implemented the most common behavior that's in clis like git.

**Comment by jdoliner** [comment]
Also, this does give you the option to pass `--no-pager`, and I wouldn't mind adding that as a config setting for pachyderm for people who really want it turned off and don't want to have to type that flag. But there's also `PAGER=cat` for that.

**Pull request merged**
