### PR TITLE
Adds from commit to pachctl.

### PR DESCRIPTION
**Pull request by jdoliner**
Add from to `get-file`

### CODE REVIEW

**Comment by jdoliner** [comment]
So for some reason this PR seems to be consistently reproducing the `Test296` bug.

**Comment by jdoliner** [comment]
Could someone +1 this for me? CI was failing before but just passed, I think it was just a case of the intermittent 296 bug, not a real failure.

**Comment by jdoliner** [comment]
@sjezewski would you mind taking a look at this one for me?

**Comment by sjezewski** [comment]
Yea I'll review now

**Comment by jdoliner** [comment]
Careful, it's a lot of code

**Comment by sjezewski** [comment]
The only thing I see missing is a test. 

Do we test the pachctl CLI interface anywhere? We probably have some test coverage of those utils somewhere else? As long as there's a test that covers the usage that we feel good about, LGTM

**Comment by jdoliner** [comment]
The actual behavior of reading with a `from` commit is covered in a few places.
We currently don't have anything covering the `pachctl` implementation, ie that when you pass `--from <commit>` it actually passes that through.

We'll need tests like that eventually I suppose, but I think it's fine for now given how simple the implementations are here.

**Pull request merged**
