### PR TITLE
Default standby feature flag

### LINKED ISSUE #4977: Standby pipelines by default
**What is the goal / desired outcome?** Add a feature flag that defaults pipelines to standby, rather than non-standby. This is behind a feature flag because it's a fairly major change, but the feature flag will be enabled in hub.

### PR DESCRIPTION
**Pull request by ysimonson**
Closes #4977

A couple of open questions:

1. Do we want to add a deployment flag for this feature flag? At the moment, there is not one, under the presumption that it'll be rare that end users will want to use this - even if it does eventually become the default.
2. We have to add a new proto field, because we can't otherwise differentiate between the user explicitly setting `"standby": false` versus just not setting it. Is the new field name (`disable_standby`) good?

### CODE REVIEW

**Comment by ysimonson** [comment]
I just manually tested it. Hooking it into automated testing would require a good amount of work, since our testing infrastructure it would require re-deploying and patching kubernetes manifests.

**Comment by nitinjainsj** [comment]
I am not sure I understand the need for "disable_standby". If the default is not set, then a user setting standby: false is redundant. Why would we want to distinguish the difference? If the default is set to true, and standby: false then we will enforce user-specified setting.

**Comment by ysimonson** [comment]
The problem is that, due to protobufs, we have no way of differentiating `"standby": false` and `"standby"` not being set at all.

**Comment by ysimonson** [comment]
I can just go ahead and add tests to this PR. I didn't originally because I feel like the LoE vs reward is not worthwhile, but if we're going to add automated tests anyways, better to add it now rather than later.

**Comment by nitinjainsj** [comment]
Automated tests should have a high return. At a high level, I am understanding that we don't have a good way to verify settings that are getting passed along the distributed systems. The reason to track in a separate issue is to discuss the merits of the solution (including is it worth doing it)

**Comment by ysimonson** [comment]
Circling back to the earlier issue, regarding having to add a `disable_standby` field.

This wouldn't be necessary if protobufs had a way of differentiating between false vs an unset boolean value. Digging in, it looks like [experimental support for field presence checks was (re-)introduced in proto3](https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md).

Unfortunately, though, it looks like [gogoprotobuf](https://github.com/gogo/protobuf), which we use, doesn't support it yet. I was trying to get a timeline, and discovered that [gogoprotobuf isn't actively maintained](https://github.com/gogo/protobuf/issues/691).

This is a bigger issue we'll need to figure out, but I'm going to hold merging this PR pending the outcome of that conversation, because, if we move back to the official protobuf golang driver, we'd be able to make use of field presence checks and therefore get rid of `disable_standby`.

**Comment by jdoliner** [comment]
I'm not sure how much presence checks actually change this feature. Because people are used to standby off as the default so I don't think it's very common for people to explicitly set it to false when they don't want it. They can obviously add that, to be explicit about it, but that requires them understanding the change and if they can do that then it's not much more work to understand the presence of disable_standby and use that instead.

**Comment by jdoliner** [comment]
Thinking about it more I'm a little worried about using presence checks in general. We've assumed in a lot of places that leaving a field unset is the same as setting it to the default value. Starting to change that might introduce a number of subtle bugs that would be a pain to track down. It might be a reasonable thing to use in migration though, so I'm not opposed to moving to a proto implementation that allows us to use it in some places, and there's other reasons to migrate to a new proto implementation. But I'm a little worried about using it as part of the user facing API.

**Comment by ysimonson** [comment]
Presence checks are opt in on a per-field basis, and as far as I can tell fully backwards compatible when you do opt in.

**Comment by ysimonson** [comment]
Per VC discussion, we're going to close this out because:

* It's confusing UX to have two flags living side-by-side (`standby` and `disable_standby`), with only one of them working depending on the feature flag's state.
* The original motivation for this was to default to standby mode on for pipelines in hub. But because of how we autoscale cluster resources on some clusters, this would actually carry a significant performance tax in some setups.

We do plan to make some improvements to standby, but they likely won't be done until pachyderm 2.0, which will open opportunities for a more thoughtful setup.

**Pull request closed without merging**
