### PR TITLE
change atom to pfs in the examples

### PR DESCRIPTION
**Pull request by ktarplee**
"atom" is deprecated as of 1.8.1

### CODE REVIEW

**Comment by JoeyZwicker** [comment]
Thanks for the PR @ktarplee. Can you sign our [CLA](https://pachyderm.wufoo.com/forms/pachyderm-contributor-license-agreement)? 

@ysimonson I believe you had some similar changes to this that you were waiting to merge as well?

**Comment by ysimonson** [comment]
Yes. The branch I have includes documentation changes as well. If we want to merge changes to examples first before changes to documentation, we could merge this PR first, followed by the one I have.

**Comment by JoeyZwicker** [comment]
I imagine we basically want to merge both since anyone running 1.8.1 will start getting the warning?

**Comment by ysimonson** [comment]
@JoeyZwicker I'm inclined to agree, but merging this PR first might make the transition a bit more seamless, because there won't be users (at least in the immediate future) that are reading through the 1.8.1 docs with pachyderm 1.8.0 or below, and confused why their PFS inputs aren't working.

**Comment by JoeyZwicker** [comment]
@ysimonson fair point. @ktarplee Thanks for signing. We'll get this merged in when we're back in the office on Wed.

**Comment by gabrielgrant** [comment]
This LGTM, but I haven't actually tested all the examples. @JoeyZwicker @Nick-Harvey or @pappasilenus  do one of you want to test this out? Or are these examples exercised by the test suite?

FWIW CI looks to be just failing because of non-team-member access to the testing enterprise token.

**Comment by ysimonson** [comment]
@gabrielgrant soon to be fixed! #3324

**Comment by ysimonson** [comment]
@ktarplee thanks again for working on this! We're just going to go ahead and merge #3320 though, since it also includes the docs changes.

**Pull request closed without merging**
