### PR TITLE
Validate file paths

### LINKED ISSUE #2614: Validate file paths
We probably only want to allow printable ASCII characters.

[See PR for a bit more discussion why this matters tactially](https://github.com/pachyderm/pachyderm/pull/2599)

### PR DESCRIPTION
**Pull request by brycemcanally**
This is intended to resolve #2614.

### CODE REVIEW

**Comment by dwhitena** [comment]
Thanks @brycemcanally! I think you were discussing this with @jdoliner. @jdoliner do you have input here?

**Comment by jdoliner** [comment]
Thanks for another great pull @brycemcanally, I'm going to get CI running on this. One other thing I'd like to see for this PR is some tests that exercise the logic. Ideally some negative (i.e. returning errors) and some positive.

**Comment by brycemcanally** [comment]
Yeah, I should have done that initially. Test cases have been added now.

**Comment by jdoliner** [comment]
You were just testing out our code review process to make sure we'd catch it :wink:

**Comment by brycemcanally** [comment]
Of course, that was why I left them out :smile:

**Comment by jdoliner** [comment]
Even though this is only half passing CI I'm going to merge it because the CI failures seem to be due to it not being able to get credentials since the code originally comes from outside our GH org. The fact that one leg of CI is passing though confirms that the code does in fact run.

**Pull request merged**
