### PR TITLE
upgrade ingress from v1beta to v1

### PR DESCRIPTION
**Pull request by tybritten**
Some ingress controllers don't treat paths without `*` as prefix types in v1beta. Also moved the `/*` to the end as the catchall

### CODE REVIEW

**Comment by chainlink** [comment]
Hi @tybritten which ingress controllers has this been tested against?

**Comment by tybritten** [comment]
I had tested it against alb and traefik but now it doesn't work on nginx if you're on 1.19+...might be time to just switch to v1. The current config doesn't work with alb

**Comment by chainlink** [comment]
Switching to v1 makes sense to me, ingress has been out of beta for a while

**Comment by tybritten** [comment]
ok updated

**Review by acohen4 — APPROVED** [review]
LGTM

**Review by acohen4 — COMMENTED** [review]
Still one failing test though

**Pull request merged**
