### PR TITLE
cmds.go(pachctl): fix grammatical error

### PR DESCRIPTION
**Pull request by jiahao**
Check it's status -> Check its status

### CODE REVIEW

**Comment by JoeyZwicker** [comment]
Thanks @jiahao. Please sign our [Contributor License Agreement (CLA)](https://pachyderm.wufoo.com/forms/pachyderm-contributor-license-agreement/) and we'll work on getting this merged

@dwhitena Can you get this merged as part of your other docs projects.

**Comment by dwhitena** [comment]
Yep @JoeyZwicker. Just let me know when the CLA is signed @jiahao!

**Comment by JoeyZwicker** [comment]
@jiahao I realize we're still waiting for the CLA before we merged this. Any chance you want to sign it even though it's just a one character change?

**Comment by dwhitena** [comment]
Fixed here: https://github.com/pachyderm/pachyderm/pull/2520. Closing.

**Pull request closed without merging**
