### PR TITLE
config: deploy dashboard by default

### PR DESCRIPTION
**Pull request by antjkennedy**
* Pachyderm dashboard is now deployed by default #2443 
* The `pachctl` flag `--dashboard` has been removed
* The `pachctl` flag `--no-dashboard` has been added
* If a new deployment is required without the dashboard please run `pachctl deploy [command] --no-dashboard`

### CODE REVIEW

**Comment by jdoliner** [comment]
Hi @antjkennedy, many thanks for the pull. Before we can get this merged we'll need you to sign or [CLA](https://pachyderm.wufoo.com/forms/m1kv71oe04eawdn/). After that we should be able to get this merged in pretty quickly.

**Comment by antjkennedy** [comment]
Hi @jdoliner I've signed the CLA, let me know if there is anything else you need.

**Comment by JoeyZwicker** [comment]
Thanks @antjkennedy. @dwhitena will review this and get it merged in.

**Comment by dwhitena** [comment]
@jdoliner @gabrielgrant Are you good with these changes? If so, I will merge in.

**Comment by jdoliner** [comment]
I'm good with them, let's see what CI says.

**Comment by dwhitena** [comment]
Hi @antjkennedy, I corrected a small merge conflict here. Also, I'm going to create a companion PR that updates the AWS, GCP, and beginner tutorial docs based on the dashboard being deployed by default. I need to have this in place when we merge for consistency. Working on that today.

**Comment by dwhitena** [comment]
@jdoliner CI passed here: https://github.com/pachyderm/pachyderm/pull/2710. Are you ok with the code changes here? If so, I will get @JoeyZwicker's ok on my companion doc changes and then merge both PRs.

**Comment by jdoliner** [comment]
Code changes LGTM.

**Comment by dwhitena** [comment]
Ok, CI is passing here: https://github.com/pachyderm/pachyderm/pull/2710. Merging.

**Pull request merged**
