### PR TITLE
Add opencv dominant color example and algorithm code base

### PR DESCRIPTION
**Pull request by SoheilSalehian**
This is for the use case for the following pachyderm/pachyderm#681.

### CODE REVIEW

**Comment by jdoliner** [comment]
@SoheilSalehian this is awesome. Thanks so much for the pull. Will work on getting this merged in next week. Only thing I want to figure out is some other way to host the data, adding 10MB to ever clone doesn't sit too well with me. I think there are some other good options we can explore though.

**Comment by SoheilSalehian** [comment]
@jdoliner thanks, regarding the input images, this PR doesn't include the `images.zip` file for the same bloating reason you mention. I was thinking of adding a script that wgets the file from google drive or something like that. Feel free to let me know if there is a more solid way to do this so we don't bloat the repo itself.

**Comment by sambooo** [comment]
A little nitpick: `examples/opencv_dominant_color_example` could probably be `examples/opencv_dominant_color` instead

**Comment by jdoliner** [comment]
Ah I see, I think you inadvertently included a few compiled binaries in the PR. Could we get those purged from the history for similar bloat reasons. Other than that this lgtm @JoeyZwicker could you do a pass on content?

**Comment by SoheilSalehian** [comment]
@jdoliner you are right, I just realized that the C++ binary (dominantColor) is 11M. This is the binary that gets copied into the container via the Dockerfile and it's the algorithm that gets run. I added a make file to download the binary from the algorithm repo.

**Comment by jdoliner** [comment]
All looks good to me. I did a `git filter-branch` to remove the binary files from the commit history so git won't store the objects. That means I need to merge this in from the CLI though.

**Comment by jdoliner** [comment]
Alright, this is in master. Closing the PR.
Thanks again for adding an awesome example @SoheilSalehian.

**Pull request closed without merging**
