### PR TITLE
Disable tests that do not work on forked repos

### PR DESCRIPTION
**Pull request by ysimonson**
This disables tests that require secrets, when the tests are being run on a forked repo. Tests continue to run the same for the main repo. With this, tests won't always fail when an outside contributor opens a PR.

Also fixed indentation of `travis.sh`. It was a mix of tabs, 4-space, and 2-space indentation.

Note that this PR is being opened from my fork of pachyderm. If the CI tests are passing, the failing tests are successfully being disabled.

### CODE REVIEW

**Comment by jdoliner** [comment]
How many tests had to be disabled as part of this?

**Comment by ysimonson** [comment]
These makefile targets are no longer run: `test-vault test-auth test-enterprise test-worker`

**Comment by gabrielgrant** [comment]
Would it make sense to just have travis detect whether it can run these tests, and just skip them if it can't, rather than disabling them completely?

**Comment by ysimonson** [comment]
That is what it's doing. Tests are only disabled if the tests are being run from a forked repo. On this repo, all tests are running as per usual.

**Comment by gabrielgrant** [comment]
oh. well then... :)

**Comment by msteffen** [comment]
Hey, sorry; taking a look at this now.

Overall I agree with the direction. Right now, it looks like https://travis-ci.org/pachyderm/pachyderm/jobs/476637077 passed even though our PFS server test failed:
```
go test -v ./src/server/pfs/server -timeout 3600s | grep -v "$(date +^%FT)"
docker: Error response from daemon: driver failed programming external connectivity on endpoint eloquent_tesla (71691e394c7ab9988f1db662ae59ec9825e63e6cb575c7082b5978524059f480): Error starting userland proxy: listen tcp 0.0.0.0:32379: bind: address already in use.
ERRO[0000] error waiting for container: context canceled 
# github.com/pachyderm/pachyderm/src/server/pfs/server [github.com/pachyderm/pachyderm/src/server/pfs/server.test]
src/server/pfs/server/server_test.go:2233:37: cannot use client (type *client.APIClient) as type client.PutFileClient in argument to "github.com/pachyderm/pachyderm/src/server/pkg/sync".PushFile:
	*client.APIClient does not implement client.PutFileClient (wrong type for Close method)
		have Close()
		want Close() error
src/server/pfs/server/server_test.go:2247:37: cannot use client (type *client.APIClient) as type client.PutFileClient in argument to "github.com/pachyderm/pachyderm/src/server/pkg/sync".PushFile:
	*client.APIClient does not implement client.PutFileClient (wrong type for Close method)
		have Close()
		want Close() error
src/server/pfs/server/server_test.go:2261:37: cannot use client (type *client.APIClient) as type client.PutFileClient in argument to "github.com/pachyderm/pachyderm/src/server/pkg/sync".PushFile:
	*client.APIClient does not implement client.PutFileClient (wrong type for Close method)
		have Close()
		want Close() error
FAIL	github.com/pachyderm/pachyderm/src/server/pfs/server [build failed]
```

I'm looking into it a little bit to try and understand what might be going on, but my only blocker as far as submitting this is answering this and the open question of why the enterprise tests weren't run in both builds

**Comment by ysimonson** [comment]
Okay, it looks like [TravisCI is working as designed](https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions), I just didn't understand push vs PR builds. PR builds trigger for PRs open from remote forks, whereas push builds trigger _only when you push to the main repo_. Because I have this branch both on the main repo, and a forked repo, it was triggering both tests. Appropriately, the push builds had access to the secrets because the code was pushed to the main repo.

**Comment by ysimonson** [comment]
The error is happening on master as well: https://travis-ci.org/pachyderm/pachyderm/jobs/477106402#L777

**Pull request merged**
