### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by derekchiang**
WIP.

### CODE REVIEW

**Comment by JoeyZwicker** [comment]
docs/faq.md doesn't exist yet. I actually have a long FAQ doc that I wrote up a few weeks ago that I need to add there (and will likely go on the website). And I think it should be "docs" not "doc" and I want to change that back. :) @jdoliner

**Comment by jdoliner** [comment]
What's being asked of me here?

**Comment by JoeyZwicker** [comment]
nothing. sorry. I'm working on a PR to add /docs/FAQ and I just wanted to let you know i'm changing "doc" to "docs." If you have a strong disagreement with that because you like everything as 3 letters, then  speak up.

**Comment by jdoliner** [comment]
Eh, I feel like this is kind of bikeshedding, but switching to docs seems a little weird to me. In my mind "docs" is short for "documents" and "doc" is short for "documentation." The latter is what we're really trying to get across since it's the more specific concept.

Also it's always a little weird to pluralize the name of a directory, since one can reasonably assume that a directory is going to hold more than one of whatever it's intended to hold. Otherwise why would it be a directory?

**Comment by JoeyZwicker** [comment]
This is 5000% bikeshedding so I'll drop it. Still irks me tho.

**Comment by jdoliner** [comment]
This LGTM. Merging.

**Pull request merged**
