### PR TITLE
Split `pachctl config set-context` into two commands

### PR DESCRIPTION
**Pull request by actgardner**
`pachctl config set-context` can accept a kube context name, but the usage is kind of obscure. When we eliminate `pachctl deploy local` we'll need a simple one-liner that creates a context based on the current kube context.

This PR introduces `pachctl config import-kube <pach context name>`, which creates a new Pach context from the current kube context. This also adds a `--namespace` flag, to support the case where we deploy into a context that isn't the default in the kube context, and `--enterprise` for deploying an enterprise server.

This should make the minikube helm deploy process as simple as `helm install && pachctl config import-kube`.

### CODE REVIEW

**Comment by chainlink** [comment]
Relatedly, I noticed I can install the helm chart and immediately use pachctl` (it seems to bootstrap a pach config with local connection for you?)

**Comment by actgardner** [comment]
I guess this is because if you have no config it makes a new empty context, and the default behaviour for an empty pach context is to use the current kube context?

**Comment by chainlink** [comment]
Starting from no `~./pachyderm/config.json` here's what it looks like after running `pachctl list repo` directly after a helm install

```
{
  "user_id": "ecd09fe6-f1e5-4556-8e9a-db5fc1b38904",
  "v2": {
    "active_context": "default",
    "contexts": {
      "default": {}
    },
    "metrics": true
  }
}
```

**Comment by actgardner** [comment]
Oh, it's definitely using port forwarding - the pachctl config supports either "implicitly" port-forwarding given a kube context, or a grpc address. I think what's surprising is that if there's no kube context specified in the pachctl config that it just uses the active context.

**Comment by chainlink** [comment]
We chatted about this offline, but have an explicit option will be good

**Comment by chainlink** [comment]
A test might be good here if it's not too much of a pain to add

**Review by chainlink — APPROVED** [review]

**Comment by chainlink** [comment]
FYI Was just going through some docs stuff with @nadegepepin  and found this https://docs.pachyderm.com/latest/deploy-manage/deploy/import-kubernetes-context/

**Pull request merged**
