### PR TITLE
Fix a bug where jobs are deleted but pods are not

### PR DESCRIPTION
**Pull request by derekchiang**

### CODE REVIEW

**Comment by jdoliner** [comment]
There's another callsite where we delete jobs here: https://github.com/pachyderm/pachyderm/blob/master/src/server/pps/server/api_server.go#L2375 could you update that one to too?

And arguably those should be using the same helper function so there's only one callsite to update

**Comment by jdoliner** [comment]
@derekchiang could we try to get this one merged ASAP, I'd like to do a point release this week that'll fix some of the disk fill up issues that people are seeing.

**Comment by derekchiang** [comment]
@jdoliner done

**Comment by jdoliner** [comment]
bhbawoeceaawsia

**Pull request merged**
