### PR TITLE
Fixed minor typo

### PR DESCRIPTION
**Pull request by brollb**

### CODE REVIEW

**Comment by JoeyZwicker** [comment]
Ditto with other PRs. LGTM. Feel free to do a bunch of typo fixes as a single PR if you want. We're flexible. :)

**Comment by brollb** [comment]
sounds good - I have a tendency to just fix whatever I see right when I see it... I can probably stop using the easy "Edit on Github" button and just add it to my existing PR :)

**Comment by JoeyZwicker** [comment]
Totally up to you. mini-PR's are great too -- just thought it might save you time by clicking fewer buttons on GH.

**Comment by jdoliner** [comment]
LGTM and CLA is signed.

**Pull request merged**
