### PR TITLE
Test PR #9251

### PR DESCRIPTION
**Pull request by msteffen**
Make sure that #9251 passes CI.

I can't seem to get CI to run on the PR directly (I now think the PR has to be created from a branch in `pachyderm/pachyderm`, rather than from a fork, regardless of the author's permissions)

### CODE REVIEW

**Comment by jerryharrow** [comment]
The problem with https://circleci.com/gh/pachyderm/pachyderm/401289 is that mount-server isn't started.  I can't actually find where that is supposed to happen.    The error is:

```
+ mkdir pfs
+ tail -F /tmp/mount-server.log
nohup: appending output to 'nohup.out'
tail: cannot open '/tmp/mount-server.log' for reading: No such file or directory
```

Below is the ci fragment.    Perhaps it should automatically be starting as part of `python3 -m pip install -e '.[dev]'`?

```
  jupyter-extension-integration-test:
    resource_class: xlarge
    machine:
      image: ubuntu-2004:202107-02
    working_directory: ~/project/jupyter-extension
    steps:
      - checkout:
          path: ~/project
      - install-python-test-deps
      - run:
          name: "Integration tests"
          command: |
            set -eux

            python3 -m venv venv
            . venv/bin/activate
            python3 -m pip install -e '.[dev]'

            nohup pachctl port-forward &

            tail -F /tmp/mount-server.log &

            mkdir pfs
            export PFS_MOUNT_DIR=$(pwd)/pfs

            # Run integration tests
            pytest -v jupyterlab_pachyderm/tests/test_integrations.py
```

**Comment by jerryharrow** [comment]
> ```
> tail: cannot open '/tmp/mount-server.log' for reading: No such file or directory
> ```

that is actually a red herring.   I found an example of the test succeeding and it  has the same failure.

https://app.circleci.com/pipelines/github/pachyderm/pachyderm/23307/workflows/d6e1a31c-ec46-481f-a830-4b5ae4009f9a/jobs/401208

**Comment by msteffen** [comment]
I believe this is due to [a change in how JupyterLab sends requests to managed services](https://github.com/jupyterhub/jupyterhub/issues/3691). I think the operative error in the logs is `Exception: You must define the 'cookie_secret' setting in your application to use secure cookies`. I haven't yet entirely figured out what the error means or how to fix it, though.

**Comment by jerryharrow** [comment]
> I believe this is due to [a change in how JupyterLab sends requests to managed services](https://github.com/jupyterhub/jupyterhub/issues/3691). I think the operative error in the logs is `Exception: You must define the 'cookie_secret' setting in your application to use secure cookies`. I haven't yet entirely figured out what the error means or how to fix it, though.

Yup.   I tracked it down to that.  The problem is that the dev-server started by test-integration.py is using the jupyter_server configuration, but is not actually running in that context.   The calls to it are hard-coded in the tests with no authorization.   I can configure the cookie_secret, but that just changes it to a 403 since the tests use no auth.    I haven't yet been able to figure out how to disable the authorization checks (the jupyter docs are not all that helpful for our use case).

**Comment by msteffen** [comment]
Closing, as this PR was replaced with https://github.com/pachyderm/pachyderm/pull/9351

**Pull request closed without merging**
