### PR TITLE
Apply JSON Patch into a fresh PodSpec structure

### PR DESCRIPTION
**Pull request by mdaniel**
Fixes: #3483

### CODE REVIEW

**Comment by jdoliner** [comment]
Hey @mdaniel thanks for fixing this, and even better adding a test for it! Only additional thing would be adding this test to our CI, but I can do that for you. I'm sure you have better things to do than dig around in our CI scripts and you've already gone above and beyond on this one.

**Comment by mdaniel** [comment]
> Only additional thing would be adding this test to our CI

That might be something worth adding to the contributing.md, and or have a checklist in that document of local tasks one should be expected to run. I admit that I was mostly relying on Travis to whine about something rather than figure out which of the 19 test make targets were safe to run _(you'll see what I mean by "safe" in the panics below)_

When I tried `make test-local`, there were several panics that seemed to imply they were not "local" as I understand that word:

```
--- FAIL: TestValidateActivationCode (62.58s)
panic: cannot get test enterprise token from s3: ExpiredToken: The provided token has expired.
        status code: 400, request id: C97C8B6B142A073D, host id: 63DQKo45F0Lb0XhuCTbkov0Fkrtk0/5XT7DkdkldwNpaZ6fbdhAAewEQAGyASHY7vMGzA5ghlJI= [recovered]
        panic: cannot get test enterprise token from s3: ExpiredToken: The provided token has expired.
        status code: 400, request id: C97C8B6B142A073D, host id: 63DQKo45F0Lb0XhuCTbkov0Fkrtk0/5XT7DkdkldwNpaZ6fbdhAAewEQAGyASHY7vMGzA5ghlJI=

goroutine 10 [running]:
testing.tRunner.func1(0xc000169100)
        /usr/local/Cellar/go/1.11.5/libexec/src/testing/testing.go:792 +0x387
panic(0x228d760, 0xc0001f87e0)
        /usr/local/Cellar/go/1.11.5/libexec/src/runtime/panic.go:513 +0x1b9
github.com/pachyderm/pachyderm/src/server/pkg/testutil.GetTestEnterpriseCode.func1()
        /Users/mdaniel/go/src/github.com/pachyderm/pachyderm/src/server/pkg/testutil/token.go:44 +0x467
sync.(*Once).Do(0x375ae20, 0x25d3408)
        /usr/local/Cellar/go/1.11.5/libexec/src/sync/once.go:44 +0xb3
github.com/pachyderm/pachyderm/src/server/pkg/testutil.GetTestEnterpriseCode(0x3732a168028f9a10, 0x5c65ad43)
        /Users/mdaniel/go/src/github.com/pachyderm/pachyderm/src/server/pkg/testutil/token.go:24 +0x39
github.com/pachyderm/pachyderm/src/server/enterprise/server.TestValidateActivationCode(0xc000169100)
        /Users/mdaniel/go/src/github.com/pachyderm/pachyderm/src/server/enterprise/server/enterprise_test.go:45 +0x22
testing.tRunner(0xc000169100, 0x25d33f8)
        /usr/local/Cellar/go/1.11.5/libexec/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
        /usr/local/Cellar/go/1.11.5/libexec/src/testing/testing.go:878 +0x35c
```

and several other "I'm trying to contact a network service" style panics.

**Comment by mdaniel** [comment]
It looks like that Travis failure was unrelated to this change; is a green Travis a pre-req for this landing?

```
=== RUN   TestExtractRestoreObjects
--- FAIL: TestExtractRestoreObjects (16.78s)
    admin_test.go:126: No error is expected but got transport: transport: the stream is done or WriteHeader was already called
    admin_test.go:126: current stack:
        goroutine 27 [running]:
        runtime/debug.Stack(0xc0001ca700, 0x1805a5b, 0x1f)
        	/home/travis/.gimme/versions/go1.11.1.linux.amd64/src/runtime/debug/stack.go:24 +0xa7
        github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/pkg/require.fatal(0x19dbba0, 0xc0001ca700, 0x0, 0x0, 0x0, 0x1805a5b, 0x1f, 0xc0001b0070, 0x1, 0x1)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:430 +0xc5
        github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/pkg/require.NoError(0x19dbba0, 0xc0001ca700, 0x19a1700, 0xc0001b0030, 0x0, 0x0, 0x0)
```

**Comment by gabrielgrant** [comment]
We do generally want CI to be green before merging, yes. I'm not familiar with this test, but just gave travis a kick to re-run in case it was just a transient network issue

**Comment by mdaniel** [comment]
This is becoming comical
> `=== RUN   TestService`
> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
> Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

which one can see here:
https://travis-ci.org/pachyderm/pachyderm/jobs/493955052#L1177

---

Separately, are these error messages expected?
* https://travis-ci.org/pachyderm/pachyderm/jobs/493955047#L260
* https://travis-ci.org/pachyderm/pachyderm/jobs/493955047#L420

**Comment by jdoliner** [comment]
CI is passing and good all LGTM, merging.

**Pull request merged**
