### PR TITLE
Pass imagePullSecret through to the underlying assets.

### LINKED ISSUE #2942: --image-pull-secret flag does not work
The `--image-pull-secret` flag to `pachctl deploy` does not work because the value it sets is not passed through in the underlying `opts` struct.

Patch in a moment.

### PR DESCRIPTION
**Pull request by jkinkead**
Fixes #2942 .

### CODE REVIEW

**Comment by msteffen** [comment]
Hey Jesse, thanks for all of these contributions! I'm copying this PR (and the other two) into private branches to get them through CI

**Comment by msteffen** [comment]
Tests passing in the internal branch: https://github.com/pachyderm/pachyderm/pull/2956

**Comment by jkinkead** [comment]
These aren't blocking us at the moment.

My goal here is to make sure that we have a documented, simple way to regenerate our k8s configs - and rolling it up into the base tool is the best (IMHO) way to do this.

**Comment by msteffen** [comment]
Thanks for the contributions!

**Pull request merged**
