### PR TITLE
Small format fixes

### PR DESCRIPTION
**Pull request by davidgasquez**

### CODE REVIEW

**Comment by jdoliner** [comment]
@davidgasquez many thanks for the pull! Everything here LGTM. There's 1 minor thing which is that CI is failing because the document you modified gets compiled as a binary asset for `pachctl` and thus needs to be recompiled. If you do `make assets` from the root of the repo and push the results it should get CI passing.

**Comment by davidgasquez** [comment]
I see! Thanks for pointing me to `make assets`. Just ran it and committed the new `assets.go` file. Let me know if I should do anything else.

**Comment by jdoliner** [comment]
@davidgasquez awesome, thanks! That should do it as soon as CI passes I'll hit the merge button.

**Comment by davidgasquez** [comment]
Nice! One thing I've noticed is that there are two types of documentation files, `.rst` and `.md`. It's probably for a specific reason but I was thinking if moving everything to Markdown would improve consistency in the formatting.

**Comment by jdoliner** [comment]
@JoeyZwicker would that work with ReadTheDocs? I think ReadTheDocs might require a RST.

**Comment by davidgasquez** [comment]
I think it should work ([PFS documentation](http://pachyderm.readthedocs.io/en/latest/pachyderm_file_system.html) is written in [Markdown](https://github.com/pachyderm/pachyderm/blob/master/doc/pachyderm_file_system.md)), although perhaps RST has more formatting options.

**Comment by davidgasquez** [comment]
Ugh, seems like the CI build is still failing! 😅

**Comment by jdoliner** [comment]
@davidgasquez yeah, unfortunately our CI can be flaky at times. Anecdotally it seems to coincide with high traffic periods such as the end of the day on Friday. I'll keep trying it, and I bet it'll pass eventually.

**Comment by JoeyZwicker** [comment]
The rst format is needed for some features of ReadtheDocs that we use. In general, docs that are mainly read on the documentation website are in rst and things that are meant to be viewed on GH (such as Readme's for examples) are md. 

For these files I think we want to keep the formats as is, but it's something we've certainly considered unifying in the future.

**Comment by davidgasquez** [comment]
Thanks for the info @JoeyZwicker! I just wanted to point this super small thing in case you missed. Makes sense to keep both formats then.

**Comment by davidgasquez** [comment]
Seems that the check are still failing... 🤔 Anything I can do?

**Comment by jdoliner** [comment]
@davidgasquez pretty sure this are spurious failures so not much to be done on your end. I'm going to rerun a few times and see if I can get it to pass.

**Comment by jdoliner** [comment]
Praise the CI gods it passed. Merging.

**Comment by davidgasquez** [comment]
Awesome! I'm deleting the branch then! 😉

**Pull request merged**
