### PR TITLE
Removed the jupyter notebook example

### PR DESCRIPTION
**Pull request by ysimonson**
The Jupyter notebook example in this repo is outdated, and does not work with modern versions of Pachyderm or Jupyter. I've ported the example to the [python client driver](https://github.com/pachyderm/python-pachyderm/pull/46), where the notebook runs on the client-side rather than as a Pachyderm service, and makes heavy use of the python client driver. I think this makes sense for a few reasons:

* All of the code is now in python, so it doesn't require the Jupyter user to know other languages in addition.
* Jupyter isn't well suited to being exposed over an insecure network. In particular, it's token-based auth isn't possible when run on Pachyderm.
* As far as I can tell, Pachyderm services don't have the same first-class support that it did when the example was made.

... however, it does mean that the client using Jupyter has to install a variety of dependencies that would otherwise be handled by docker.

### CODE REVIEW

**Comment by gabrielgrant** [comment]
It certainly seems like some of the way this is set up today isn't ideal, but my inclination is to want to figure out a good story for how Jupyter can run within the cluster (likely using services), rather than rip it out completely and make people egress any data they want to play with. I agree the command-line output, token-based auth obviously doesn't make sense in a pach service, but there must be other ways of doing this. Do you know how Jupyter Hub does it's auth? (my impression is they at least used to separate users on the server using unix users, but not sure how they wall off access to the notebooks' web front-ends and the notebook's kernel socket)

Also, what were the "other (non-python) language" requirements you mention?

**Comment by ysimonson** [comment]
I'm not sure how Jupyter Hub does stuff.

By other languages, I mean that this Jupyter demo intermixes python, go, bash and make. The new Jupyter demo is just python.

**Comment by ysimonson** [comment]
Looks like they setup their own [custom auth](https://github.com/jupyterhub/jupyterhub/wiki/Authenticators). AFAICS, it's not possible to do this outside of jupyter hub.

**Comment by gabrielgrant** [comment]
As discussed in slack: my preference would be for us to come up with a better story around running jupyter within a pach cluster, but given we haven't had the chance to do that yet, I think we're best removing this -- leaving a broken example kicking around as a to-do item isn't very helpful for anyone. Instead, I've added an issue to track this in #3681

**Pull request merged**
