### PR TITLE
Expose glob capture and replace in cli

### PR DESCRIPTION
**Pull request by adelelopez**
Will be useful for debugging join inputs that are behaving unexpectedly.

### CODE REVIEW

**Comment by jdoliner** [comment]
cc @svekars

**Comment by mindthevirt** [comment]
Is this covered in the new `pachctl list datum` functionality?

**Comment by nadegepepin** [comment]
Removing the `needs docs` label at this level. It has been added to the feature request #5624

**Comment by msteffen** [comment]
Closing this PR, as it's obsolete.

**Pull request closed without merging**
