### PR TITLE
First implementation of debug sos

### PR DESCRIPTION
**Pull request by brycemcanally**

### CODE REVIEW

**Comment by jdoliner** [comment]
This all looks reasonable to me except I think you're vendoring the wrong thing here. I only see one file which is the main function for a CLI for Archiver, not the library you're importing. I suspect this won't compile on CI. It's up to you but I don't think you really need to include an outside library for creating tar archives, the go standard library has good support for both tar and gzip, I just whipped up this program which works with the tar command line utility:

```golang
package main

import (
	"archive/tar"
	"compress/gzip"
	"io"
	"os"
)

func main() {
	gw := gzip.NewWriter(os.Stdout)
	defer func() {
		if err := gw.Close(); err != nil {
			panic(err)
		}
	}()
	w := tar.NewWriter(gw)
	defer func() {
		if err := w.Close(); err != nil {
			panic(err)
		}
	}()
	for _, name := range os.Args[1:] {
		f, err := os.Open(name)
		if err != nil {
			panic(err)
		}
		fi, err := f.Stat()
		if err != nil {
			panic(err)
		}
		hdr, err := tar.FileInfoHeader(fi, "")
		if err != nil {
			panic(err)
		}
		if err := w.WriteHeader(hdr); err != nil {
			panic(err)
		}
		if _, err := io.Copy(w, f); err != nil {
			panic(err)
		}
		if err := f.Close(); err != nil {
			panic(err)
		}
	}
}
```

**Comment by brycemcanally** [comment]
Yeah, I noticed that issue when CI failed. I vendored the path that was given for getting the command line tool not the library. I figured it might be useful to have a general purpose archiving utility available vs hand coding using what go has available. I mean, it is only one line of code to create the file vs how many are in that program.

**Comment by jdoliner** [comment]
I'm cool with vendoring the lib, this seems right on the cusp to me between worth it to bring in a library vs. just rolling our own from the stdlib, so either way is fine by me.

**Comment by jdoliner** [comment]
Other things that might be nice to have in the sos:
- `kubectl get all`
- logs from pachd and workers
- system information (would be nice for debugging fuse)

**Comment by brycemcanally** [comment]
This PR is subsumed by: #5116

**Pull request closed without merging**
