### PR TITLE
Job logs

### PR DESCRIPTION
**Pull request by jdoliner**

### CODE REVIEW

**Comment by jdoliner** [comment]
@derekchiang would you mind taking a look at this for me?

**Comment by derekchiang** [comment]
It seems a little weird to me that we simply concatenate all pod logs together.  For certain workloads, I can imagine a very confusing output.

Maybe we can do it similar to how `docker-compose` does it?

https://calazanblog-assets.s3.amazonaws.com/media/editor-uploads/docker_compose_logs.png

See that each line is started with a pod name.  In our case, pods do not have names, so maybe just `pod_1`, `pod_2`, `pod_3`...

Also, it could be cool if when you run `pachctl get-logs` while the job is running, you get a nice continuous output so you can watch your jobs in real time.

**Comment by derekchiang** [comment]
Or maybe have `pachctl get-logs` require two arguments which are `job-id` and `pod`, where `pod` is just a number from 0 to the number of pods.  Then it'd just print the log for that pod.

**Comment by jdoliner** [comment]
@derekchiang anything else you'd like changed here or is this good to merge?

**Comment by derekchiang** [comment]
LGTM

**Pull request merged**
