### PR TITLE
Delete repo returns bool

### PR DESCRIPTION
**Pull request by lemontree-ca**
Opened a new PR so that it's easier to incorporate master's changes for API and repos. Original PR: https://github.com/pachyderm/pachyderm/pull/9094

### CODE REVIEW

**Review by brendoncarroll — CHANGES_REQUESTED** [review]
Remove
- `src/pfs/20230815_make_proto_log3`
- `worker_init`

**Comment by lemontree-ca** [comment]
removed src/pfs/20230815_make_proto_log3 and worker_init

**Review by kevyang — APPROVED** [review]
approved for integrations/python sdk

**Review by brendoncarroll — APPROVED** [review]
LGTM

**Pull request merged**
