### PR TITLE
Add deprecation warnings

### PR DESCRIPTION
**Pull request by robert-uhl**
With the addition of the Helm chart, the following `pachctl deploy`
flags are deprecated and will be removed in the future:

 - dash-image
 - dashboard-only
 - no-dashboard
 - expose-object-api
 - storage-v2
 - shards
 - no-rbac
 - no-guaranteed
 - static-etcd-volume
 - disable-ssl
 - max-upload-parts
 - no-verify-ssl
 - obj-log-options
 - part-size
 - retries
 - reverse
 - timeout
 - upload-acl

### CODE REVIEW

**Review by echohack — CHANGES_REQUESTED** [review]
Hi @robert-uhl 

As part of these changes we need a few docs updates. This should land in both the 1.13.x and master branches.

- deprecation warnings in the CHANGELOG.md at the root of the repo.
- feature deprecation notice in /doc/docs/master/contributing/supported-releases.md

I'm also tagging @nadegepepin for review on these items to make sure they land successfully. Thank you! <3

**Review by jdoliner — APPROVED** [review]
All LGTM

**Comment by nadegepepin** [comment]
LGTM - I updated the contribution/supported_releases page to mention the deprecation of some 'pachctl deploy" flags.

**Review by nadegepepin — APPROVED** [review]

**Review by echohack — APPROVED** [review]
Looks good now! Got the CHANGELOG.md updated in master with #5872

**Comment by msteffen** [comment]
Just FYI, I changed `deprecationWarning` to print to `stderr` in https://github.com/pachyderm/pachyderm/pull/5871 to shephard that PR through CI.

Unfortunately, without that fix, `deprecationWarning` causes our CI tests to fail, because `pachctl deploy --dry-run` emits JSON that includes the deprecation warning (which `kubectl apply -f -` then can't parse). I think this was maybe merged while testfaster was having scaling issues, but just to state such explicitly, for posterity: you can see the state of CI on a PR in `pachyderm/pachyderm` by looking at the "checks passed" section on this comments page, and ideally all of the `ci/circleci` checks should be passing.

**Pull request merged**
