### PR TITLE
Update helm url in docs

### PR DESCRIPTION
**Pull request by tybritten**

### CODE REVIEW

**Comment by tybritten** [comment]
@chainlink are we good to change this now? also, this will still work for 1.x charts too, right?

**Review by nadegepepin — APPROVED** [review]
LGTM

**Comment by chainlink** [comment]
Great minds! https://github.com/pachyderm/pachyderm/pull/6767

**Comment by tybritten** [comment]
closed for https://github.com/pachyderm/pachyderm/pull/6767

**Pull request closed without merging**
