### PR TITLE
Bump k8s version to 1.2.0

### PR DESCRIPTION
**Pull request by jdoliner**
Addresses #172.

### CODE REVIEW

**Comment by JonathanFraser** [comment]
I suspect the apiserver is not coming up correctly, seems like they dropped the cluster-name parameter, or at least its not available. 
There is also a deprecation warning on portal-net and address flags, they seem to have be superceeded by service-cluster-ip-range and insecure-bind-address instead

**Comment by jdoliner** [comment]
@JonathanFraser thanks for the heads up. I'm doing merges all day, this is next up so hopefully will have this working and in master by eod today.

**Comment by jdoliner** [comment]
I've hit a strange issue on this. `make test` passes locally... somehow when it runs on travis I get a database error saying that the database `"pachyderm"` hasn't been initialized. Does anyone conceive of a hypothesis to test here?

@sjezewski

**Comment by JonathanFraser** [comment]
I was having some issues with this locally myself, it seemed like pachd could not contact the rethinkdb database. I kept trying to do that on a subnet that didn't seem to exist anywhere in the container.

**Comment by jdoliner** [comment]
I saw a similar thing and I think I figured it out. Between 1.1 and 1.2
they seem to have made it so the kubelet starts its own proxy as a pod.
Previously the proxy was created by our script. This meant that we were
starting 2 proxies which led to problems.

**Comment by jdoliner** [comment]
Alright, CI is green on this one so as soon takes a look at this and gives me a +1 I'll merge.
Quick summary of changes since this ballooned a little.

- Bumps us to version 1.2 of Kubernetes
- This led to a few refactors with the k8s startup scripts, several files got deleted
- K8s changed the default for image pulling so I had to change our manifest slightly
- the test container went away, we now just run tests using go test, much simpler

**Comment by sjezewski** [comment]
Woah cool - I love the tests simplification!

The rest looks good too.

**Pull request merged**
