### PR TITLE
Fix websocket port forward port 32082->38081

### PR DESCRIPTION
**Pull request by gabrielgrant**
Makes it consistent with the [internal (8081)](https://github.com/pachyderm/pachyderm/blob/master/src/server/pkg/deploy/assets/assets.go#L867) and [external (30081)](https://github.com/pachyderm/pachyderm/blob/master/src/server/pkg/deploy/assets/assets.go#L870) ports exposed by the container, as well as what the [dash currently connects to by default](https://github.com/pachyderm/dash/blob/master/app/services/pachd.js#L25)

### CODE REVIEW

**Comment by jdoliner** [comment]
Could we also make it so that the error messages that get printed when the UI isn't up get swallowed?

**Comment by gabrielgrant** [comment]
Added as #1767

**Comment by gabrielgrant** [comment]
This PR fixes #1753

**Comment by jdoliner** [comment]
Fixes #1767

**Comment by sjezewski** [comment]
Looks like the PR build fails because the path to `etc/build/travis.sh` moved ... I'll take a look

**Pull request merged**
