### PR TITLE
Expose service annotations

### LINKED ISSUE #3754: Expose `annotations` field
**What is the goal / desired outcome?**

We need to allow annotation attachment for service pipelines in order to run the services behind Ambassador.

**If there is a way to accomplish this today via workaround, what does that require?**

It just requires adding a new `annotations` field to the proto schema and then passing this data to the kubernetes client

### PR DESCRIPTION
**Pull request by cfga**
Allows users to set service annotations to service pipelines.

Closes #3754

### CODE REVIEW

**Comment by cfga** [comment]
I am having problems with passing tests in travis. From some point, an error is thrown:

```
No error is expected but got transport is closing
```

**Comment by cfga** [comment]
Hi Pachyderm team,

I have a problem running tests for this PR. The goroutine at `pachyderm/src/server/pachyderm_test.go:8846` does not  stop its execution after the test is finished and blows up after successful test pass (does kafka go down?). It is also present in the last build for this PR: https://github.com/pachyderm/pachyderm/pull/3751. Would not it be better to stop this goroutine? Did not dig really deep into this, but this looks wrong.

```
=== RUN   TestKafka
--- PASS: TestKafka (9.60s)
=== RUN   TestDeferredProcessing
--- PASS: TestDeferredProcessing (7.59s)
=== RUN   TestPipelineHistory
panic: Fail in goroutine after TestKafka has completed
goroutine 1946 [running]:
testing.(*common).Fail(0xc0001bac00)
	/home/travis/.gimme/versions/go1.11.1.linux.amd64/src/testing/testing.go:546 +0x135
testing.(*common).FailNow(0xc0001bac00)
	/home/travis/.gimme/versions/go1.11.1.linux.amd64/src/testing/testing.go:568 +0x2b
testing.(*common).Fatal(0xc0001bac00, 0xc00008df18, 0x1, 0x1)
	/home/travis/.gimme/versions/go1.11.1.linux.amd64/src/testing/testing.go:628 +0x6f
github.com/pachyderm/pachyderm/src/server.TestKafka.func1(0xc00039f860, 0xc0003852c0, 0xc0001bac00)
	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/pachyderm_test.go:8852 +0x1ef
created by github.com/pachyderm/pachyderm/src/server.TestKafka
	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/pachyderm_test.go:8846 +0xc0d
FAIL	github.com/pachyderm/pachyderm/src/server	851.943s
Makefile:489: recipe for target 'test-pps-helper' failed
make: *** [test-pps-helper] Error 1
```

**Comment by cfga** [comment]
BTW, does this PR have something to do with the problem? Seems related

https://github.com/pachyderm/pachyderm/pull/3752

**Comment by cfga** [comment]
Overall, looks like it fails randomly

**Comment by adelelopez** [comment]
Yeah, that's a bug -- thanks for catching that!

**Comment by jdoliner** [comment]
Code all looks good to me. The only thing I'd like to see added to this is some test coverage. Should be as simple as adding an annotation in the `TestService` and then checking to make sure that it's present. After that this should be good to merge.

**Comment by cfga** [comment]
@jdoliner Done!

**Comment by cfga** [comment]
@jdoliner no problem! rebased & regenerated the proto file

**Comment by cfga** [comment]
Just thought that it might be a good idea to exclude the generated proto files from the repo altogether, as this approach is somewhat error-prone in general and also spoils the picutre on additions/deletions in this particular case. What do you think?

**Comment by cfga** [comment]
Not in this PR, of course =)

**Comment by cfga** [comment]
@jdoliner is there smth else up for a fix?

**Comment by jdoliner** [comment]
@cfga nope, sorry for the delay. I'll get this merged today.

**Pull request merged**
