### PR TITLE
force unix style paths on put file

### PR DESCRIPTION
**Pull request by desmo953**
force unix style paths for pachctl put so that functionality is same when used on native windows.

### CODE REVIEW

**Comment by jdoliner** [comment]
@desmo953 many thanks for the PR. Unfortunately I don't think this can work as is because the path could also be a URL and modifying it would cause the request to fail. I'm a little unsure if it makes sense to modify windows paths like this in a way that's opaque to the user. You should be able to get the same result by doing something like this:

```sh
$ pachctl put file repo@master:/unix/style/path -f windows\style\path
```

but if we are going to do this it needs to only apply to the path if it's not a URL.

**Comment by desmo953** [comment]
@jdoliner thanks for the comment, and I will consider how to better implement this idea.  

As for `pachctl put file repo@master:/unix/style/path -f windows\style\path` the problem lies when a recursive put is used in windows, the items will show up on pachyderm with \ and is not recognized properly as folder paths.

**Comment by jdoliner** [comment]
@desmo953 I see, that makes sense. The easiest design here might just be putting it behind a flag, that way there's no surprises for the user.

**Comment by msteffen** [comment]
Closing this PR as obsolete

**Pull request closed without merging**
