### PR TITLE
first draft of workflow examples

### PR DESCRIPTION
**Pull request by pappasilenus**
This is an outline of the structure of examples that can be used to set up workflows for our customers.   Please tell me what you think...

### CODE REVIEW

**Comment by pappasilenus** [comment]
@JoeyZwicker This might be a good thread to talk about the information architecture you had in mind.

**Comment by JoeyZwicker** [comment]
Jimmy and I talked about this a bit more today. I think overall the info architecture is going to look something like:

- Overview: Here are the 5 steps in a Pachyderm dev workflow. Change code, docker build, docker push w/ tag, update json, update pipeline. Jimmy will likely steal a bunch of info from the currently existing "individual workflow" doc. There are also 3 main ways this flow can be automated for faster iteration. 
        
     - local environment with `--build` flag
     - Pachyderm Build Pipelines (python or Core Pach)
     - CI Systems (includes GHA example)


I think all of the above apply to both individuals and teams (although CI is heavily weighted more towards teams) so that distinction doesn't need exist here. Jimmy and I also talked about the next higher-level doc and workflow that is team oriented. This will include some or all of: dev-->staging--> prod branches/clusters, resource isolation & sharing, data sharing and development, pipeline templates, etc. Any system that includes these collab features ALSO includes the above development workflows (such as CI).

**Comment by JimmyWhitaker** [comment]
Sorry, took me a get a handle on all of this. Here's the rough sketch of the pages that I think make sense and the flow of them. Most of the content is already there. This would just be a light restructuring to accommodate the new components.  Let me know what you think.

## Working with Data and Pipelines
Minor changes to what already exists [here](https://docs.pachyderm.com/latest/how-tos/individual-developer-workflow/)
- How it works (Diagram of steps)
- Data Workflow - Load Your Data into Pachyderm
- Step 1: Write Your Analysis Code	
- Step 2: Build Your Docker Image
- Step 3: Push Your Docker Image to a Registry
- Step 4: Create/Edit the Pipeline Config	
- Step 5: Deploy/Update the Pipeline

## Enhanced Pipeline Workflow
"The manual build steps to update a pipeline can be tedious, so we’ve created two ways to automate the steps required to update a pipeline..."

**-- build**
  - Mostly used when iterating on the Docker image and minor code modifications
  - Automates the Docker build, modify pipeline, and run pipeline steps
  - Link to details described here: https://docs.pachyderm.com/latest/how-tos/updating_pipelines/

**Build pipelines** - https://github.com/pachyderm/pachyderm/pull/5064
  - Used Earlier stage where there’s more frequent changes to your code 
  - Don't have to wait for the image to build locally
  - Uses cloud infrastructure (only pushes code files)
  - Note: Can't use with Hub yet

**Python-pachyderm** Create Pipeline
  - [Create python pipeline](https://pachyderm.github.io/python-pachyderm/python_pachyderm.m.html#python_pachyderm.create_python_pipeline) using python objects from the python_pachyderm Python module
  - Similar to Build pipelines, but leverages the python-pachyderm client (if controlling pachyderm pipelines from python code).

## CI/CD Integration
- Essentially everything from [this](https://docs.pachyderm.com/latest/how-tos/team-developer-workflow/)
- Github Actions
- Jenkins Integration

**Comment by JoeyZwicker** [comment]
I think this is great Jimmy. The only thing I'm not 100% sure about is whether we call this "two ways to automate the steps required to update a pipeline..." or "four" or "three". haha.  I think your overall categories of "enhanced" and "CI/CD" is ok, but I'm having trouble drawing lines between them all. I guess the "enhanced" ones are "pachyderm will automated steps 2 through 5 for you" and CI/CD is "your CI system does that"?... that might be a good line honestly. The way that --build works versus the other two enhanced ones is totally different though. In same ways I almost think that --build is closer to the CI/CD method, except that we use your local docker daemon to be "CI" for you, whereas the python and build pipelines and are very specific (and weirder) pattern. 

This seems like a good conversation for Tech Office Hours at 11am PT tomorrow. @jdoliner tends to have great intuition on this kind of stuff.

**Comment by JoeyZwicker** [comment]
Not to increase the scope of this project at all, but @pappasilenus or @JimmyWhitaker, once we have the GHA action example ready, how easy/hard would it be to get it into this marketplace? https://github.com/marketplace?category=deployment&type=actions

I'm working on perhaps trying to get GH/m12 PR to help highlight this "integration" so being in the marketplace probably adds to their interest in that.

**Comment by JimmyWhitaker** [comment]
> Not to increase the scope of this project at all, but @pappasilenus or @JimmyWhitaker, once we have the GHA action example ready, how easy/hard would it be to get it into this marketplace? https://github.com/marketplace?category=deployment&type=actions
> 
> I'm working on perhaps trying to get GH/m12 PR to help highlight this "integration" so being in the marketplace probably adds to their interest in that.

This could be really interesting. I'll look into it, so we can discuss.

**Comment by JimmyWhitaker** [comment]
I sketched out the docs that overlap with this work in this PR [here](https://github.com/pachyderm/pachyderm/pull/5184).

**Comment by msteffen** [comment]
Closing this PR, as it's obsolete

**Pull request closed without merging**
