### PR TITLE
Bump Go versions

### PR DESCRIPTION
**Pull request by HaraldNordgren**

### CODE REVIEW

**Comment by HaraldNordgren** [comment]
Not sure what is happening here? Do the new build jobs require their own credentials?

Possibly the main symptom:
```
You should consider upgrading via the 'pip install --upgrade pip' command.
++pachctl enterprise get-state
+[[ No Pachyderm Enterprise token was found = \N\o\ \P\a\c\h\y\d\e\r\m\ \E\n\t\e\r\p\r\i\s\e\ \t\o\k\e\n\ \w\a\s\ \f\o\u\n\d ]]
+set +x
download failed: s3://pachyderm-engineering/test_enterprise_activation_code.txt to - Unable to locate credentials
expected 1 arguments, got 0
Usage:
  pachctl enterprise activate activation-code [flags]
Flags:
      --expires string   A timestamp indicating when the token provided above should expire (formatted as an RFC 3339/ISO 8601 datetime). This is only applied if it's earlier than the signed expiration time encoded in 'activation-code', and therefore is only useful for testing.
  -h, --help             help for activate
Global Flags:
      --no-metrics   Don't report user metrics for this command
  -v, --verbose      Output verbose logs
+pachctl auth list-admins
the auth service is not activated
+admin=admin
+echo admin
+pachctl auth activate
(1) Please paste this link into a browser:
https://github.com/login/oauth/authorize?client_id=d3481e92b4f09ea74ff8&redirect_uri=https%3A%2F%2Fpachyderm.io%2Flogin-hook%2Fdisplay-token.html
(You will be directed to GitHub and asked to authorize Pachyderm's login app on GitHub. If you accept, you will be given a token to paste here, which will give you an externally verified account in this Pachyderm cluster)
(2) Please paste the token you receive from GitHub here:
Retrieving Pachyderm token...
error activating Pachyderm auth: Pachyderm Enterprise is not active in this cluster, and the Pachyderm auth API is an Enterprise-level feature
make: *** [test-vault] Error 1
The command "etc/testing/travis.sh" exited with 2.
```

**Comment by jdoliner** [comment]
@HaraldNordgren yeah this is a permissioning issue, I'll get CI running for you.

**Comment by jdoliner** [comment]
CI running in #3197

**Comment by jdoliner** [comment]
Closing this so we don't have 2 PRs.

**Comment by jdoliner** [comment]
Hey @HaraldNordgren this is all ready to merge, I just need one more thing which is for you to sign our [CLA](https://pachyderm.wufoo.com/forms/pachyderm-contributor-license-agreement/), even for small stuff like this we still like to cover our bases with a CLA.

**Comment by HaraldNordgren** [comment]
@jdoliner Filled in the CLA. I guess the PR you want to merge is: https://github.com/pachyderm/pachyderm/pull/3197

**Pull request closed without merging**
