### PR TITLE
Update fruitstand

### PR DESCRIPTION
**Pull request by jdoliner**

### CODE REVIEW

**Comment by jdoliner** [comment]
This pr mostly involves updates to the fruit stand demo, some to make it work with changes that have happened since the last time I demoed, some where improvements like adding an explicit image.

There is one actual change in here which is that I added colors to `list-job`.

**Comment by jdoliner** [comment]
@sjezewski can has review?

**Comment by sjezewski** [comment]
What do you use `docker-build-fruitstand` for? 

Other than that, changes LGTM

**Comment by jdoliner** [comment]
`docker-build-fruitstand` build an image called `fruitstand` which is used by the pipeline in the demo.

This was one of the changes @JoeyZwicker and I decided to make, the fruitstand image is empty in that it's just a copy of our `job-shim` but it makes it more clear to the user that they can use their own images and how that works.

**Comment by sjezewski** [comment]
Got it - I see the new image specified in pipeline.json

LGTM then

**Pull request merged**
