### PR TITLE
Fix link to OpenCV pipeline

### PR DESCRIPTION
**Pull request by ferrouswheel**

### CODE REVIEW

**Comment by JoeyZwicker** [comment]
Thanks Joel! Can you sign our [CLA](https://pachyderm.wufoo.com/forms/m1kv71oe04eawdn/) and then we can get this merged.

**Comment by ferrouswheel** [comment]
Have signed the CLA - cheers @JoeyZwicker

**Comment by JoeyZwicker** [comment]
@sjezewski What's the new process to merge this now?

**Comment by JoeyZwicker** [comment]
CI passed on #1986. merging.

**Pull request merged**
