### PR TITLE
Troubleshooting guide

### PR DESCRIPTION
**Pull request by sjezewski**
I added the start of the troubleshooting guide. Most of it deals w deployment issues.

I'm not sure where exactly to put it, where to link to it. @dwhitena @JoeyZwicker - suggestions?

### CODE REVIEW

**Comment by dwhitena** [comment]
@sjezewski Thanks!  Some of these will go under a planned best practices section, which will also include some of Derek's recent additions.  I will be standardizing all of this for the 1.5 release and organizing it.  I suggest one of the following:

- just merging the `*.md` files here somewhere in docs without linking them, then I could organize them and standardize with the other things as I'm going through them, or
- just add these to another PR I'm working on for standardizing/adding best practices.  I'm happy to massage them.

Let me know what you prefer.

**Comment by sjezewski** [comment]
Oh I also want to add a few items to debug disk pressure issues. Most of them are now mitigated since we use `emptyDir` but there is still at least one failure pattern.

**Comment by sjezewski** [comment]
The recipes make sense to go under best practices. What about the troubleshooting guide? Where should that go?

**Comment by gabrielgrant** [comment]
Having "Troubleshooting" be a new top-level subsection within "Reference" makes the most sense to me

**Comment by dwhitena** [comment]
I think the plan was to have a section that includes best practices, troubleshooting, etc., Not necessarily a section named "best practices." Something like "managing a Pachyderm cluster" or something more concise.  We already have quite a few sections.

**Comment by sjezewski** [comment]
OK. So you're good to merge this as is @dwhitena ?

I do think the stuff I added under 'troubleshooting' should live in a separate doc. I tried hard to keep it in the 'symptom' and 'recourse' format. And there are things in common between some of those examples.

**Comment by dwhitena** [comment]
Yes, @sjezewski let's go ahead and merge and then I will re-arrange as I add the rest of the 1.5 docs.

**Pull request merged**
