### PR TITLE
[CORE-1914] Warn, not error, on nonexistent contextual project

### PR DESCRIPTION
**Pull request by robert-uhl**
Print pretty error details if available, otherwise just print the message (on the off chance that it’s a not-found but not project–not-found error).

Example output:

```
$ pachctl list repo
2023-08-17T16:24:38.113-0400    ERROR   client/client.go:618    WARNING: Could not inspect project "non-existent-project": error getting project "non-existent-project": project "non-existent-project" not found
PROJECT NAME CREATED SIZE (MASTER) DESCRIPTION
```

### CODE REVIEW

**Review by jrockway — COMMENTED** [review]
I'd be inclined to rename version_warnings to warnings, and use the existing warning handling machinery here.  I don't think this special case deserves as much code as it has; include the InspectProject error in the warnings, and the client can deal with it as it sees fit.

The warning remains misleading in the presence of `--project` flags, or RPCs that don't need the project.  I think that individual RPC handlers need to return "project not found" when that's the problem; I have a PR out that does that.

Not your fault, but I think this was a poorly-thought-out feature request that we shouldn't have done.

**Comment by robert-uhl** [comment]
> I'd be inclined to rename version_warnings to warnings, and use the existing warning handling machinery here.

That makes sense. No concerns about renaming the message field?

**Comment by jrockway** [comment]
No concerns about renaming the field.  Adjust the `version_warnings_ok` one as well.

**Review by jrockway — APPROVED** [review]
Good cleanup!

**Review by brendoncarroll — APPROVED** [review]

**Review by smalyala — APPROVED** [review]

**Pull request merged**
