### PR TITLE
Faq

### PR DESCRIPTION
**Pull request by JoeyZwicker**

### CODE REVIEW

**Comment by jdoliner** [comment]
CI's broken. Blame @JoeyZwicker

**Comment by JoeyZwicker** [comment]
Travis doesn't have support for FAQs...

**Comment by jdoliner** [comment]
Pretty sure that's it. Travis saw we added `FAQ.md` and was like "omg guys, I can't handle frequently asked questions, I can hardly handle infrequently asked questions."

@sjezewski do you think it's worth reaching out to the travis guys to see if they can make it more tolerant?

**Comment by sjezewski** [comment]
Totes.

Got 'em on the phone right now and I'm reading our FAQ to them line by line to see what's causing the error.

They're based in Germany so this is a long distance call (3$/minute). Don't worry, I'll expense it.

**Pull request merged**
