### PR TITLE
Adds tests for Overwrite+Split.

### PR DESCRIPTION
**Pull request by jdoliner**

### CODE REVIEW

**Comment by dwhitena** [comment]
I think this looks ok for committing the same file twice.  Is it just checking that the number of files is as expected though?  My questions were mostly around whether or not the datums generated by the split were the same and/or were replaced.

**Comment by jdoliner** [comment]
Yeah, it's just checking file count, which I think is a pretty good indication that overwrite is working correctly. I'll make the content different between the puts and check that it's right though. Just to be safe.

**Comment by jdoliner** [comment]
@dwhitena ok, it checks for the right content too now.

**Comment by dwhitena** [comment]
Awesome.  LGTM @jdoliner!

**Pull request merged**
