### PR TITLE
Added "--reprocess" for the update-pipeline

### PR DESCRIPTION
**Pull request by sillystring13**
Use "--reprocess" for update-pipeline to manually trigger jobs for the update

### CODE REVIEW

**Comment by jdoliner** [comment]
Many thanks for the pull @sillystring13 before we can get this merged we'll need you to sign our [CLA](https://pachyderm.wufoo.com/forms/pachyderm-contributor-license-agreement/).

Other than that everything LGTM.

**Comment by jdoliner** [comment]
Closing this due to oldness. @sillystring13 this is good to merge as soon as you sign the CLA. Feel free to reopen or comment here if you decide you want to sign it.

**Comment by sillystring13** [comment]
Apologies for the lateness - the form is signed

**Comment by JoeyZwicker** [comment]
Actually, It looks like this was already updated (not quite the same way) on our end in the interim. Re-closing, but thanks again for the CLA and PR @sillystring13. We always love contributions like this!

**Pull request closed without merging**
