### PR TITLE
Makes init job idempotent again.

### PR DESCRIPTION
**Pull request by jdoliner**
This prevents the annoying scenario where the second time you deploy you're left with an init job in CrashLoop.

### CODE REVIEW

**Comment by derekchiang** [comment]
Potential inaccurate PR name.  Not sure if init job was ever idempotent :P

**Comment by jdoliner** [comment]
I feel like I have a distinct memory of a time when it was. I feel like I used to be able to do:

```
make clean-launch-dev && make launch-dev
```
to my hearts content and it wouldn't leave around an init job. Maybe I just imagined that though?

**Comment by sjezewski** [comment]
Yea it definitely used to be. I think we broke it w the refactor. Taking a look now

**Comment by sjezewski** [comment]
image

**Comment by jdoliner** [comment]
Epic meme :)

**Pull request merged**
