### PR TITLE
update det helm templates 0.27.1 for 2.9.0

### PR DESCRIPTION
**Pull request by molinamelendezj**
for unified installer det sha e05d57dfd5e2e97fc551b965092dd0fedcd9102f for 0.27.1 det release

### CODE REVIEW

**Comment by molinamelendezj** [comment]
@BOsterbuhr I was confused about this [PR](https://github.com/pachyderm/pachyderm/commit/3c4b39fefbda58cb717471eacfe403c46ebf4f4b). Did you make these changes on top, or brought them over from det repo?

**Review by djanicekpach — APPROVED** [review]

**Comment by molinamelendezj** [comment]
> > Did you make these changes on top, or brought them over from det repo?
> 
> @molinamelendezj some are from the EE repo and then the ` determined.integrations.pachyderm.address` is not in their helm chart yet but needs to be in ours.

gotcha. we can do this a separate PR then.

**Comment by molinamelendezj** [comment]
> These changes don't include the changes in the determined-EE helm chart.

@BOsterbuhr  I was told there shouldn't be any chart changes in EE; they should only be changed in OSS. So if there are changes there in EE they have not been committed back or released yet. this PR is just the supported 0.27.0 release commits. NOT what is in their main unreleased.

**Comment by BOsterbuhr** [comment]
> > These changes don't include the changes in the determined-EE helm chart.
> 
> @BOsterbuhr I was told there shouldn't be any chart changes in EE; they should only be changed in OSS. So if there are changes there in EE they have not been committed back or released yet. this PR is just the supported 0.27.0 release commits. NOT what is in their main unreleased.

From a customer UX perspective, we have to add the changes that are in the 0.27.1 release as well as add our own section for the `determined.integrations.pachyderm.address`. If we don't, the combined installer won't work as it should, and users will have to manually update the master-config secret every time they do a helm upgrade.

**Comment by molinamelendezj** [comment]
Needs to ship with #9678

**Review by BOsterbuhr — APPROVED** [review]
LGTM

**Pull request merged**
