### PR TITLE
Make the worker gRPC port configurable via env vars

### LINKED ISSUE #3365: pipeline services allocate port 80 as "grpc-port"; this needs to be configurable by env var
Unclear to me all of what this port is for (worker statuses?), but if it is used, it will cause problems in OpenShift, since it's privileged (#3334)

This should be read from an env var, instead of hard coded, and will also need to be propagated from pachd to pipeline pods (#3363)

Alternatively, for the sake of getting openshift working, pretty sure this could just be changed to be hard-coded to be a non-privileged port (8080?) instead of 80

### PR DESCRIPTION
**Pull request by ysimonson**
Fixes #3365

### CODE REVIEW

**Comment by ysimonson** [comment]
Some tests are timing out, and the errors are reproducible locally, but I haven't been able to track down why yet.

I'm running `go test ./src/server -run TestFlushCommit` locally, and the test times out after 10m. This is opposed to running the same test on master, which finishes after a little more than 2m. Notes:

* The timeouts are happening here: https://github.com/pachyderm/pachyderm/blob/462145baade0514ffbfa47637711945e1c3917ea/src/server/pachyderm_test.go#L1091
* `pc list-job` indicates all jobs finished successfully. All run in 30s or less. However, the sum of durations is over 10m, so that be the culprit, but that doesn't explain why the test runs fine on master.
* `pc get-logs` is not indicating any errors.
* `pc get-logs --job [job] --raw` is not indicating any errors.
* `kc logs [pod] user` (i.e. kubernetes' logs for the various pipeline pods' user containers) is not showing any obvious errors.

**Comment by ysimonson** [comment]
@jdoliner assigning you as reviewer since you're already helping a bunch with figuring out why it's broken

**Comment by ysimonson** [comment]
The problem was that, there's two constructors for the debug API server, and one of them wasn't modified to take in the port. As a result, API servers constructed with the second constructor had a port value of 0. The second constructor was used by sidecars, which would eventually time out or crash when they couldn't connect to a debug server on port 0.

I'm not sure why this wasn't reflected in the logs. Maybe pachctl doesn't show sidecar logs?

**Comment by ysimonson** [comment]
@jdoliner I'm also working on changing the variable name (it's called PPS worker port, gRPC worker port, and gRPC port in various places) to debug port, and it's default from 80 to 649. What do you think? https://github.com/pachyderm/pachyderm/compare/configurable-worker-grpc-port...rename-worker-grpc-port

**Comment by gabrielgrant** [comment]
Is anything else needed to get this merged?

**Comment by ysimonson** [comment]
Just need @jdoliner's review

**Pull request merged**
