### PR TITLE
Updated CreatePipeline to take a *pps.Transform

### PR DESCRIPTION
**Pull request by Southclaws**
When creating pipelines, `image`, `cmd` and `stdin` wasn't enough and I wondered why `CreatePipeline` didn't allow specifying things like environment variables, image secrets, etc.

### CODE REVIEW

**Comment by jdoliner** [comment]
I'm not sure if changing the signature of `CreatePipeline` in this way is something we want to do. Most of the point of the go client is that it saves you having to construct a bunch of objects inline such as `Transform`. If you strongly desire this behavior we could consider adding it as a `CreatePipelineTransform` method or something like that but right now I don't see a lot of benefit to being able to specify the `Transform` as a struct rather than function arguments.

**Comment by Southclaws** [comment]
Alright, that makes sense (I wasn't sure on this either but noticed the next argument was a `pps.ParallelismSpec` object so I just copied).

I will simply replicate the arguments for a `Transform` in this function then. This is all because pretty much all of our pipeline images require `Env` and `ImagePullSecrets` and I wondered why these weren't available in the `CreatePipeline` function. I suppose an even better approach could be to un-marshal a JSON string directly into a Pipeline request like how `pachctl create-pipeline` works?

**Comment by jdoliner** [comment]
Yeah, making those available in the function signature is definitely reasonable.
When using a `client` you can always call `client.PpsAPIClient.CreatePipeline` and pass it a `CreatePipelineRequest` directly. You can define that request inline as go code or parse an embedded json string to get it. Both should work.

**Comment by Southclaws** [comment]
I actually investigated `client.PpsAPIClient.CreatePipeline` when looking at how `APIClient.CreatePipeline` did it, but I'm not entire sure what to do about the `ctx` argument.

**Comment by jdoliner** [comment]
For context you can just pass: `context.Background()` and add `import "golang.org/x/net/context"` to the top of your file. You can also use that parameter to specify timeouts and cancel operations.

**Comment by Southclaws** [comment]
Alright brilliant thanks! (as you can probably tell, I'm rather new to the Go language and it's patterns!)

**Comment by jdoliner** [comment]
Closing since we've realized the change isn't necessary, feel free to keep asking questions here.

**Pull request closed without merging**
