### PR TITLE
Fixing Link to Pachyderm's github site.

### PR DESCRIPTION
**Pull request by maxknee**
Link was broken.

### CODE REVIEW

**Comment by jdoliner** [comment]
Many thanks for the pull. Would you mind signing our [CLA](https://pachyderm.wufoo.com/forms/pachyderm-contributor-license-agreement/) and I'll get this merged in as soon as CI is green.

**Comment by maxknee** [comment]
Done and done.

**Comment by maxknee** [comment]
Can this get merged?

**Comment by JoeyZwicker** [comment]
Definitely! Sorry about the slowness on that one. :)

**Pull request merged**
