### PR TITLE
Better proto

### PR DESCRIPTION
**Pull request by jdoliner**
With this PR `make proto` should work for anyone who has docker installed.
It uses Derek's proto container but rather than sharing a volume (which won't work with docker-machine) it uses tar.

### CODE REVIEW

**Comment by derekchiang** [comment]
A huge milestone in the history of this project

**Comment by jdoliner** [comment]
It will forever be remembered as the day protoeasy got even easyier

**Comment by jdoliner** [comment]
Could someone give this a quick look for me? Assuming CI passes I want to get this merged asap so I can use it.

**Comment by derekchiang** [comment]
LGTM

**Pull request merged**
