### PR TITLE
Support yaml input spec in datum mounting

### PR DESCRIPTION
**Pull request by smalyala**
Currently, the input spec can only be JSON. Add support for YAML since PPS pipeline specs can be in YAML and it's more readable than JSON. After mounting datums, automatically format input specs to be YAML.

Jira: https://pachyderm.atlassian.net/browse/INT-696

### CODE REVIEW

**Comment by pleeko** [comment]
Are we only allowing Yaml as input or is JSON also allowed?

**Comment by smalyala** [comment]
> Are we only allowing Yaml as input or is JSON also allowed?

Both are allowed.

**Review by pleeko — APPROVED** [review]
nit: You should add a happy path case for YAML in the Datum tests.

**Comment by smalyala** [comment]
Added!

**Pull request merged**
