### PR TITLE
Register healthServer for pachd in pfs mode

### LINKED ISSUE #1818: Large jobs get stuck in restart loop with 'context cancelled' error
I was seeing this on a customer data set, and an independent customer reported as well.

The logs we're seeing were of the form:

```
2017-05-09T22:31:00Z ERROR job 14a3207f-451a-4838-9089-8a1692a9616c failed to process datum [file_info:<file:<commit:<repo:<name:"config" > id:"bf54fc96051542f0a7800232cc5a2af1" > > file_type:DIR size_bytes:751 children:"config.py" hash:" \305\235&\203\240Fo#\306\025\034\343\251\245\222\314\200\322\214%\302s\203\350\036\014\303\037\010\373C" > name:"config"  file_info:<file:<commit:<repo:<name:"full_data" > id:"0915af5e09bf4571904520007cfd1d5a" > > file_type:DIR size_bytes:21024966858 children:"background" children:"human" hash:"\322\261\037\224o\342vZ\016\224\030\260\177\275U<t\250z\016V}\024\263a\014\r\214\263\236\360n" > name:"full_data" ] with: Process() call failed: rpc error: code = 2 desc = context canceled, retrying in: 714.630908ms
```

And would happen within a few seconds of the job starting. (We'd see the request received / downloading input messages).

After debugging (by overloading the context.cancel std lib) ... we narrowed down the source of the cancel to `client.KeepConnected` which once debug output was added provided the error:

```
HealthClient ERROR! rpc error: code = 12 desc = unknown service health.Health
```

And inspecting pachd's main function we see we don't register the health server when running in pfs mode in the sidecar.

Because `KeepConnected` runs after 5s ticks ... if all datums could be downloaded within that 5s window ... the job would succeed ... otherwise it would fail. That's why this bug only appeared on larger data sets.

### PR DESCRIPTION
**Pull request by sjezewski**
fixes #1818

### CODE REVIEW

**Comment by derekchiang** [comment]
This is some HOF bug candidate here.  To provide some context (credits goes to @sjezewski and @msteffen for identifying the issue), our Golang client internally embeds a health check loop which fires every 5 seconds.  What this means is that if a client connects to a server that doesn't have a health check endpoint (which is how the sidecar server is), then any request that takes more than 5 seconds to complete will fail because the health check will fire and fail.

**Comment by sjezewski** [comment]
I'm realizing I'd like to write a test for this.

I think if I make a job that sleeps for 5 seconds we should see the issue.

**Comment by sjezewski** [comment]
No that won't work ... because the client that is trying to KeepConnected is between the worker and the sidecar pachd/pfs

So it needs to be during the file download phase.

We run the integration tests on travis CI using the filesystem as the obj store ... so we'd need to write a datum that takes more than 5s to read from disk. Googling HD read speeds ... thats ~100MB/s ... so we'd need to write a file > 500MB, prob about 1G to be sure. Not sure this is the best use of an integration test, but could be a good load test?

What do you think @msteffen ?

**Comment by sjezewski** [comment]
Discussing w Matt I think we'll have good coverage for this w the load test harness.

**Pull request merged**
