### PR TITLE
Adds `reason` field to list-job.

### PR DESCRIPTION
**Pull request by jdoliner**
Few users discover the `reason` field for jobs because it's only present in `inspect-job` and not `list-job`.
This display the message in `list-job` as well. The downside is that it makes the lines looong.
We could do a few things:
- merge this as is, shells wrap lines for a reason and it's not that bad.
- abbreviate the line to the first 20 characters or something like that.
- remove the output commit field, that's always the longest field and it seems like the least useful, since people normally are just reading from `master` to get the latest complete results.

### CODE REVIEW

**Comment by jdoliner** [comment]
I'd love to have more opinions on the above. Here's an example of what it looks like now:

```
➜  pachyderm git:(reason_in_list_job) ✗ pachctl list-job
ID                               OUTPUT COMMIT                                         STARTED        DURATION           RESTART PROGRESS  DL UL STATE                                                                                                       
eab040ec83614c70937ba1238a498891 pipeline69a6e2c9163c/e1bac109825b480ebbc105b4aeadbec1 54 seconds ago Less than a second 0       0 + 0 / 1 0B 0B failure: failed to process datum: 902882cfc4d4024423cd2577f27f0a39ca7b74de90f7295869e4a9930934c7c3 
```

**Comment by JoeyZwicker** [comment]
I like removing output commit. As you said, that's the lead commonly used info i ever need to grab from list-job. 95% of the time I'm just grabbing the commit directly from `output_repo master`

**Comment by JoeyZwicker** [comment]
Limiting the message length a bit could also be reasonable -- not sure what the right char length is though.

**Comment by JoeyZwicker** [comment]
wait, actually -- the important info in list0job output commit is the output repo -- that's what i look at to see what pipeline a given job was. So it still needs the repo name (same as pipeline name), just not the commit ID. Just wanted to clarify that

**Comment by jdoliner** [comment]
Yeah, I realized that too as I was playing around with the command. I think that should be title `Pipeline` rather than `Output Repo` though, it's shorter and probably clearer. The one other thing that occurred to me is that if you do `list-job --pipeline foo` then those values will be the same for every job, we may want to elide them in that case since it's redundant and useless info.

**Comment by jdoliner** [comment]
I also added the last job state in list-pipeline. Output now looks like this:

```
➜  pachyderm git:(reason_in_list_job) pachctl list-pipeline 
NAME                 INPUT                                   CREATED           STATE / LAST JOB                    
pipelinea30cb903dfff TestPipelineFailure_data1c3eca4a4f4c:/* About an hour ago running / failure 
➜  pachyderm git:(reason_in_list_job) pachctl list-job     
ID                               PIPELINE             STARTED           DURATION           RESTART PROGRESS  DL UL STATE                                         
d1f6ec497c974eb895dce5591ccc9c51 pipelinea30cb903dfff About an hour ago Less than a second 0       0 + 0 / 1 0B 0B failure: failed to process datum:...
```

**Comment by jdoliner** [comment]
Yeah, I agree, de-uglifying all of those uuids floating around would probably make this problem go away.

**Pull request merged**
