### PR TITLE
Bump kubernetes to 1.4

### PR DESCRIPTION
**Pull request by jdoliner**

### CODE REVIEW

**Comment by jdoliner** [comment]
Sadly, my commit to fix CI broke CI :(

**Comment by jdoliner** [comment]
@msteffen whenever you have a chance, also would you mind giving a run on your machine. I remember k8s 1.3 worked on some devices and not others so we should test this one too. The upgrade was painless for me this time so I'm hopeful it will be for you too.

**Comment by jpoon** [comment]
Do the vendored dependencies also need to be updated to 1.4? The https://github.com/pachyderm/pachyderm/blob/master/src/server/vendor/vendor.json#L1218, looks like it is pointing to somewhere between 1.2 and 1.3. 

(I'm a go-newb so sorry if this is a stupid question)

**Comment by jdoliner** [comment]
@jpoon not stupid at all, updating the vendored dependencies seems like a good idea so I'm going to do it. Judging by the fact that CI is passing it seems like k8s backward compatibility is good enough that it's not strictly necessary. But still, it's best to be up-to-date.

**Comment by jpoon** [comment]
Awesome. Thanks @jdoliner! Coincidentally, updating the k8s vendored dependencies to 1.4 will be needed for the Azure work (https://github.com/pachyderm/pachyderm/issues/960) as data-disk volume support was introduced in the last release.

**Comment by msteffen** [comment]
LGTM. For some reason, I sometimes run out of file descriptors when I run the tests in minikube. But when I finally gave up on that, this runs fine when I run it in dockerized kubernetes

**Comment by jpoon** [comment]
@jdoliner, ETA on getting this merged? It's needed for volume mounting portion of https://github.com/pachyderm/pachyderm/issues/960.

**Comment by jdoliner** [comment]
@jpoon will try to get this merged in by eod today. Just haggling with `govendor` to get things compiling.

**Comment by jdoliner** [comment]
@jpoon done! Apologies for the delay.

**Pull request merged**
