### PR TITLE
Allow JSON or YAML output from deploy command.

### PR DESCRIPTION
**Pull request by jkinkead**
Partial fix for #1079 .

We're using custom deploys and need YAML for our k8s configs.

### CODE REVIEW

**Comment by jdoliner** [comment]
Linting can be run with `make lint` I'll add it to the contributing guide. Thanks for your help!

**Comment by jkinkead** [comment]
I'll work on cleaning this up today! Is there a unit testing guide for contributors? I was lazy about tests, and didn't see a reference to what you typically run.

**Comment by jdoliner** [comment]
@jkinkead tests can be run with `make test` although it's a bit finicky and normally encounters an error on local machines if you try to run the entire test suite from scratch. CI runs it though so I'd just rely on that.

**Comment by jkinkead** [comment]
Yeah, I hit a couple of errors trying to get it working locally.

The linter now succeeds, but the Travis tests are failing due to something new - connecting to the kubectl port forwarder, possibly?

**Comment by jdoliner** [comment]
@jkinkead yeah, we get intermittent failures on Travis where Kubernetes doesn't come up for us. We haven't been able to determine quite what causes it, we normally just rerun the CI when that happens. I just hit the button for you.

**Comment by jdoliner** [comment]
Alright, CI is passing. Merging.

**Pull request merged**
