### PR TITLE
Improve docs to list Added Valid Log Levels

### PR DESCRIPTION
**Pull request by jabhishek87**
fixed Issue #5289 
added description for valid log levels
https://github.com/pachyderm/pachyderm/issues/5289

Signed-off-by: AbhishekJ <ia.malhotra@gmail.com>

### CODE REVIEW

**Comment by JoeyZwicker** [comment]
@jabhishek87 This looks great. My only follow up ask is can you make the same changes to the same file in the 1.11.x directory here as well: https://github.com/pachyderm/pachyderm/tree/master/doc/docs

Docs changes should go into master as well as the current release directory unless the change is for a future feature only. In this case, these are great changes we'd love to have in 1.11.x docs branch too.

**Comment by jabhishek87** [comment]
> @jabhishek87 This looks great. My only follow up ask is can you make the same changes to the same file in the 1.11.x directory here as well: https://github.com/pachyderm/pachyderm/tree/master/doc/docs
> 
> Docs changes should go into master as well as the current release directory unless the change is for a future feature only. In this case, these are great changes we'd love to have in 1.11.x docs branch too.

Done with the changes, in the respective files, 
regarding that on the docs branch, will cherry-pick once it gets merged into master, That's the way I think , let me know your views

**Comment by JoeyZwicker** [comment]
Perfect. Our docs build system will automatically push these changes to the branches within the docs system so you don't need to cherrypick anything.

**Comment by jabhishek87** [comment]
Thanks can you add the Hacktoberfest-accepted tag,

**Pull request merged**
