### PR TITLE
Implement DeleteCommit

### PR DESCRIPTION
**Pull request by derekchiang**

### CODE REVIEW

**Comment by jdoliner** [comment]
sean-bean-lgtm

**Comment by jdoliner** [comment]
Nuts to think how many times we've had to work around not being able to delete commits and it's like 30 lines of code...

**Comment by derekchiang** [comment]
I think I was reluctant to implement `DeleteCommit` this way mostly because it lacks any sort of atomicity guarantees.  If you delete commits from a branch that's concurrently being worked on by other clients, it can easily get into a corrupted state.

**Comment by derekchiang** [comment]
I'm going to add a warning message to pachctl actually, to tell people that this is a dangerous feature.

**Pull request merged**
