### PR TITLE
Replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`

### PR DESCRIPTION
**Pull request by Juneezee**
The `github.com/ghodss/yaml` package is no longer being actively maintained. `sigs.k8s.io/yaml` is a permanent fork of `github.com/ghodss/yaml`, which is actively maintained by Kubernetes SIG and widely used in K8s projects.

The notable change is that `github.com/ghodss/yaml` uses `gopkg.in/yaml.v2 v2.2.2`, while `sigs.k8s.io/yaml` uses `gopkg.in/yaml.v2 v2.4.0`. You can see the changes between the two versions here: [v2.2.2...v2.4.0](https://github.com/go-yaml/yaml/compare/v2.2.2...v2.4.0), which mostly consists of bug fixes.

### CODE REVIEW

**Comment by FahadBSyed** [comment]
looks good to me. Your changes were tested against our CI system and passed, barring a few flakes. I reran the flakes and they passed on subsequent retries.

**Review by FahadBSyed — APPROVED** [review]

**Comment by Juneezee** [comment]
Rebased and resolved a conflict in `go.mod`

**Comment by Juneezee** [comment]
Rebased and resolved a conflict in `go.mod`

**Comment by Juneezee** [comment]
Hi @jrockway , sorry for the explicit mention. I would be grateful if you could take some time to review the changes and provide me with your feedback. If there are any specific concerns or questions you have about the changes, I am more than willing to help address them.

**Comment by jrockway** [comment]
This looks good to me and I appreciate the go.mod cleanup.  I'll merge after I figure out whether or not you need a CLA for this; I'm asking internally.

**Comment by Juneezee** [comment]
Hi @jrockway . It's been a while and I wanted to follow up regarding the status of my pull request. Could you please provide an update on whether a CLA is required for this particular contribution? I appreciate your time and assistance. Thank you.

**Comment by Juneezee** [comment]
Hi @jrockway . It's been a while and I wanted to follow up regarding the status of my pull request. Could you please provide an update on whether a CLA is required for this particular contribution? I appreciate your time and assistance. Thank you.

**Comment by Juneezee** [comment]
Hi @jrockway . It's been a while and I wanted to follow up regarding the status of my pull request. Could you please provide an update on whether a CLA is required for this particular contribution? I appreciate your time and assistance. Thank you.

**Comment by Juneezee** [comment]
Friendly ping @jrockway

**Comment by jrockway** [comment]
I never got an answer about the CLA.  The Github check says it passed, so I'm OK with merging it.  Can you rebase and `bazel run //:gazelle`?  Otherwise I'll fork it and run Gazelle.

**Comment by Juneezee** [comment]
@jrockway Thanks for the swift reply. I have rebased and run `bazel run //:gazelle`. Please take a look again. Thank you.

**Comment by jrockway** [comment]
Thank you, look good!  CI is doing it's thing.  I'll press the merge button when it's done.

**Comment by Juneezee** [comment]
@jrockway Sorry, I missed out a leftover from the `git rebase`. Please re-run the CI again :bowing_man:

**Comment by jrockway** [comment]
Haha, I was just adjusting that.  You will also need:

```patch
diff --git a/MODULE.bazel b/MODULE.bazel
index ad392bbc2e..1ea88fd854 100644
--- a/MODULE.bazel
+++ b/MODULE.bazel
@@ -184,7 +184,6 @@ use_repo(
     "com_github_felixge_httpsnoop",
     "com_github_fsnotify_fsnotify",
     "com_github_fsouza_go_dockerclient",
-    "com_github_ghodss_yaml",
     "com_github_go_logr_zapr",
     "com_github_go_sql_driver_mysql",
     "com_github_golang_protobuf",
```
(MODULE.bazel will also auto-update; you can run `bazel run //:buildozer 'use_repo_remove @gazelle//:extensions.bzl go_deps com_github_ghodss_yaml' //MODULE.bazel:all` to replicate what I did.

I have that additional change in my branch that's doing the CI run, which you can follow here: https://app.circleci.com/pipelines/github/pachyderm/pachyderm?branch=jonathan%2FJuneezee%2Fchore%2Fyaml

**Comment by jrockway** [comment]
I saw your update to include that diff.  That code is passing all the tests, so the time has finally come to merge!

Thank you for working through this, I always appreciate cleanups like this!

**Comment by Juneezee** [comment]
> I saw your update to include that diff. That code is passing all the tests, so the time has finally come to merge!
> 
> Thank you for working through this, I always appreciate cleanups like this!

You too. Thank you for your time and help :heart: !

**Pull request merged**
