### PR TITLE
Windows support for pachctl. First version.

### PR DESCRIPTION
**Pull request by abourget**
Certain things might not work, but the thing compiles and runs usefully
under Windows.

Could be advertised as `beta` for Windows :)

### CODE REVIEW

**Comment by abourget** [comment]
When using `get-file` and doing some `--recursive`, it seems the code uses `filepath.Join()` or something, as it uses backslashes even to pass file locations to `etcd`. I think those occurrences should be using `path.Join()` instead... It works for OS X and Linux, but some such uses will break under Windows.

**Comment by derekchiang** [comment]
Thanks for the patch; supporting `pachctl` on Windows would be wonderful.

There are two other changes I would like to see before we merge this PR:

* As you said, we need to fix the `filepath` versus `path` issue.
* Update the release process to include building and releasing `pachctl` for Windows.

**Comment by sjezewski** [comment]
Because of the recent changes to the `~/.pachyderm/config` file ... I think we'd need that code updated (as well as any code that checks for env vars?)

See this comment: https://github.com/pachyderm/pachyderm/pull/2005/files#diff-396f93197d0a15fc1d7c95feedc343f5R116

**Comment by JoeyZwicker** [comment]
This is outdated so closing for now. @abourget We'd be happy to help you update this PR if you want to get it merged.

**Pull request closed without merging**
