### PR TITLE
Fix bogus --raw output in pachctl

### LINKED ISSUE #2932: pachctl list-file --raw appends pretty output to raw
See bottom of output:
```
$ pc list-file input master
NAME                TYPE                SIZE                
0                   file                104B                
0000000000000001    file                2B                  
0000000000000002    file                2B                  
0000000000000003    file                2B      
$ pc list-file input master --raw
{
  "file": {
    "commit": {
      "repo": {
        "name": "input"
      },
      "id": "e3b0429950aa4347a09c784c27587d3c"
    },
    "path": "0000000000000001"
  },
  "fileType": "FILE",
  "sizeBytes": "2",
  "hash": "NknN9yS+NCOpuo4uFJp8bs2qSI6E2kV45X6qRiYVpwU="
}{
  "file": {
    "commit": {
      "repo": {
        "name": "input"
      },
      "id": "e3b0429950aa4347a09c784c27587d3c"
    },
    "path": "0000000000000002"
  },
  "fileType": "FILE",
  "sizeBytes": "2",
  "hash": "jq1vkhrWOTNB8cZLB4Ay6ccq4lCUUrNqdsVc+iY9hmw="
}{
  "file": {
    "commit": {
      "repo": {
        "name": "input"
      },
      "id": "e3b0429950aa4347a09c784c27587d3c"
    },
    "path": "0000000000000003"
  },
  "fileType": "FILE",
  "sizeBytes": "2",
  "hash": "Qpme+p5ET5vRjZuyswOslZ8XxbH5BThJe9vsc9/hxT4="
}NAME                TYPE                SIZE                
0                   file                104B                
0000000000000001    file                2B                  
0000000000000002    file                2B                  
0000000000000003    file                2B                  
```

### PR DESCRIPTION
**Pull request by mdaniel**
This fixes the following `--raw` defective commands:

* `glob-file`
* `list-datum`

and while `list-job` was not currently defective, it used the code pattern that would make it susceptible to the same fall-through bug

this more-or-less fixes #2932 but I didn't check `flush-commit` or `subscribe-commit`, so caveat go-ator

### CODE REVIEW

**Comment by jdoliner** [comment]
Much thanks for the pull @mdaniel code all lgtm, I'll merge this as soon as CI passes.

**Comment by mdaniel** [comment]
Given that CI did not pass for what I presume is just a flakey build, can you poke Travis to have it try again?

**Comment by gabrielgrant** [comment]
@mdaniel poked

**Comment by jdoliner** [comment]
LGTM, merging.

**Pull request merged**
