### PR TITLE
Format correction for json spec

### PR DESCRIPTION
**Pull request by benjaminsims**

### CODE REVIEW

**Comment by JoeyZwicker** [comment]
Good catch @benjaminsims. Can you sign our [CLA](https://pachyderm.wufoo.com/forms/pachyderm-contributor-license-agreement)?

**Comment by JoeyZwicker** [comment]
On second thought, @jdoliner aren't these docs autogenerated? So is this something that needs to be fixed elsewhere?

**Comment by derekchiang** [comment]
Yeah it's autogenerated from here: https://github.com/pachyderm/pachyderm/blob/master/src/server/pps/cmds/cmds.go#L153

Should probably also fix this while we are at it:

https://github.com/pachyderm/pachyderm/blob/master/src/server/pps/cmds/cmds.go#L510

**Comment by JoeyZwicker** [comment]
@sjezewski  Does this still need to be merged? If so, can you take a look at this since its auogenerated docs stuff

**Pull request closed without merging**
