### PR TITLE
Run tests with Go 1.8 in CI

### PR DESCRIPTION
**Pull request by philipithomas**
Related to #1346

### CODE REVIEW

**Comment by derekchiang** [comment]
I think this is just changing the CI environment?  I think what we really want is to use Go 1.8 to compile pachyderm.  The way it works is that we use this Docker image to compile our code, so the patch will necessarily involve updating this Dockerfile to use Go 1.8 instead: https://github.com/pachyderm/pachyderm/blob/master/Dockerfile

**Comment by philipithomas** [comment]
It runs all of the tests in the CI environment. At least, everything compiles and (unit) tests pass in both Go 1.7 and Go 1.8. I guess that, for some of the functional tests, it's using the 1.8 compiled version. Because these changes are NOOP on Go 1.7, I think they should be merged ASAP, and that you should keep the CI changes so that any incoming changes are Go 1.8-compatible. Then, when you're ready to officially upgrade to Go 1.8, you can update the Dockerfiles.

**Comment by derekchiang** [comment]
I see.  I changed the title of the PR to better reflect the content.

I think we might as well remove the Go 1.7 environment.  I don't see any reason why we'd want to run two copies of the test suites in parallel, especially considering that our CI is already heavily loaded.  Can @sjezewski chime in?

**Comment by jdoliner** [comment]
@philipithomas many thanks for the pull. This is awesome. CLA is signed and this all looks good to me so I'm going to merge!

**Pull request merged**
