### PR TITLE
Automate release

### LINKED ISSUE #381: One liner to install on linux
Would be nice to be able to `apt-get install pachctl`

### LINKED ISSUE #490: Provide pre-built binaries for easier installs
We can make a release CI job that creates the pre-built binaries for platforms we want to support.

This will allow the homebrew recipe to just download a binary. This would make the install a lot quicker.

(right now the brew formula declares go as a dependency ... so I think that means it will install it if it DNE ... but it takes a minute or so to install even with go already present)

And this would allow us to provide pre-packaged linux installs as well via #381

### LINKED ISSUE #511: Make version numbers prettier and not so spammy.
I think we should change our version numbers to look like `1.0.0` rather than `1.0.0(849)` having a random build number in there that doesn't mean anything to users is a bit weird.

Also while we're at it I don't think we need anywhere near as many tagged versions as we have. I don't think we've used any of the tags besides `1.0.0(849)` for all the other versions people have just been spinning the server up directly from the repo so the commit hash acts as a de facto version number.

### LINKED ISSUE #512: Automate Releasing
Releasing now involves several steps:

- building / tagging / releasing pachd
- updating the manifest (regenerating the versioned / unversioned local files and committing that change / updating the hosted copy)
- releasing pachctl

And soon we'll be building a bunch of binaries for pachctl via #490 

There are enough things here to make this easy to miss details, so lets automate this and separate this from CI testing. (We definitely don't want to build binaries for every CI run).

We can have a special rule for a 'release' branch that CI detects, or we can figure out a way to make a totally separate job. Whatever makes more sense.

### LINKED ISSUE #530: Release Tagging is broken on CI
There's an error in the `make tag-release` task at the end of the job. CI jobs will pass, but won't be tagged. 

Looks like change broke something in pedge's library.

Either we fix this, or setup the new release CI job. This needs to be resolved one way or another before we actually release 1.1. I'd rather spend time working on the way we want it to work going forward -- #512

### LINKED ISSUE #537: Fix CLI help output from brew version of pachctl
Since we use a wrapper script (and cobra uses something like argv[0]) it misreports the binary name in the help output.

```
$ pachctl
Access the Pachyderm API.

Envronment variables:
  ADDRESS=0.0.0.0:30650, the server to connect to.

Usage:
  _pachctl [command]

Available Commands:
  repo             Docs for repos.
  create-repo      Create a new repo.
  inspect-repo     Return info about a repo.
  list-repo        Return all repos.
  delete-repo      Delete a repo.
  commit           Docs for commits.
  start-commit     Start a new commit.
  finish-commit    Finish a started commit.
  inspect-commit   Return info about a commit.
  list-commit      Return all commits on a set of repos
  flush-commit     Wait for all commits caused by the specified commits to finish and return them.
  list-branch      Return all branches on a repo.
  file             Docs for files.
  put-file         Put a file from stdin
  get-file         Return the contents of a file.
  inspect-file     Return info about a file.
  list-file        Return the files in a directory.
  delete-file      Delete a file.
  mount            Mount pfs locally.
  job              Docs for jobs.
  create-job       Create a new job. Returns the id of the created job.
  inspect-job      Return info about a job.
  get-logs         Return logs from a job.
  list-job         Return info about jobs.
  pipeline         Docs for pipelines.
  create-pipeline  Create a new pipeline.
  inspect-pipeline Return info about a pipeline.
  list-pipeline    Return info about all pipelines.
  delete-pipeline  Delete a pipeline.
  run-pipeline     Run a pipeline once.
  version          Return version information.

Flags:
  -h, --help   help for _pachctl

Use "_pachctl [command] --help" for more information about a command.
```

We just use the wrapper script to supply the build version (the final version string). In the future if we want to be able to support versions like `v1.0.1(RC)` I think we'd still need this mechanism. But, I'll revisit this when we do our automated release update. If we choose to just run with versions like `v1.0.1` this problem will go away (because we won't need the wrapper).

### PR DESCRIPTION
**Pull request by sjezewski**
Fixes #512 
Fixes #511 
Fixes #530 
Fixes #537 
Fixes #490 
Fixes #381 

## Summary

To release all of our software, you can now:

- checkout master
- run `make VERSION_ADDITIONAL=RC1 release` to perform the release

If you don't have the right github tokens / s3 tokens / github repo access / etc, the script will fail and should report the access you're missing.

## Release Endpoints

- `pachd` -- is built w the additional version specified, tagged, and pushed to [docker hub](https://hub.docker.com/r/pachyderm/pachd/tags/)
- `job-shim` -- the same thing happens
- manifests
    - the versioned (`etc/kube/pachyderm-versioned.json`) and unversioned (`etc/kube/pachyderm.json`) manifests are updated and committed in the pachyderm repository
    - the versioned manifest is published to the website, which means its:
        - copied and committed to the `www` repo
        - uploaded to S3, so that its available at `https://pachyderm.io/manifest.json`
- `pachctl`
    - Is updated via homebrew (the homebrew repo is updated / committed / pushed)
    - Is available via for install on linux via a one liner: `curl -o /tmp/pachctl.deb -L https://pachyderm.io/pachctl.deb && dpkg -i /tmp/pachctl.deb`
        - Which means that the deb file gets committed to `www` repo / uploaded to S3

## Versioning

- We simplified versioning a lot. Now versions look like `1.0.1-foo`
- We no longer tag builds on travis (tagging is only done at release time via the `release` make task)
- We can put any RC or other string we want
- or if no `AdditionalVersion` is supplied, it'll contain the commit hash that was used to compile it

This has the nice side effect that when doing `make launch` it'll always be a released version, and when doing `make launch-dev` it will always contain the hash of the repo when the image was built.

### CODE REVIEW

**Comment by jdoliner** [comment]
cmcscw

Last step is me testing on my machine right?

**Comment by sjezewski** [comment]
Haha. Yup. Todos from testing on JD's machine:

1) Update setup.md to include linux one liner
2) Fail (and stop) if goxc not configured (missing GH token)
3) Fail if sha256sum not found
4) Update www script to upload single file
5) Make sure we can supply a blank string (for no additional version)
6) Remove commented lines in release task ... and output message to ask user to push to complete release

**Comment by sjezewski** [comment]
Ok, did each of the things above.

The one exception is that uploading a single file doesn't work for larger files. I've opened an issue on the www repo to track this.

Also ... it made me very happy to remove most of the docs under the release instructions.

Once the builds pass again, I'd like you to run the script locally again @jdoliner , but this time test a point release, so:

1) increment the micro version in `src/client/version/version.go`
2) run `make point-release`

Then we'll have `v1.0.2` released. If you'd rather test a pre-release, I'm ok w that too. In that case, no code changes, just:

`make VERSION_ADDITIONAL=RCblah release`

**Comment by sjezewski** [comment]
And fixed #600 while I was in there. Now we have true separation between pachctl installs (without go!) and pachyderm cluster deployment!

**Pull request merged**
