### PR TITLE
Migrations

### PR DESCRIPTION
**Pull request by derekchiang**
Add a script that migrates data from 1.2.2 to 1.2.3.  Also some documentations.

### CODE REVIEW

**Comment by JoeyZwicker** [comment]
As we discussed offline, we should move the documentation for this to a relevant section (either advanced or misc probably make the most sense for now until we add a production section). Make sure to update the relevant table of contents too.

**Comment by derekchiang** [comment]
@JoeyZwicker done

**Comment by JoeyZwicker** [comment]
docs move part LGTM. Someone else will have to comment on the actual code.

**Comment by jdoliner** [comment]
LGTM

**Pull request merged**
