### PR TITLE
Update go.pedge.io vendoring, move from protolog to protolion

### PR DESCRIPTION
**Pull request by peter-edge**
This does an update for all go.pedge.io vendoring, along with github.com/gengo/grpc-gateway, and a run with make proto. I am moving from protolog to lion, https://go.pedge.io/lion - it's the same concept and same code mostly, but proto stuff is specifically in the proto sub-package, and abstracted away. This package is named protolion, and is almost equivalent to protolog, minus most global configuration being in the lion package instead of protolion. I also have done https://go.pedge.io/pb, which replaces https://go.pedge.io/google-protobuf.

### CODE REVIEW

**Comment by peter-edge** [comment]
Ping - with the new commits, this has gotten out of date, sending over this stuff as a courtesy, can you check it out?

**Comment by jdoliner** [comment]
Protolion is breaking for us, seems like there's some new assumptions about what types of data are logged.
```
github.com/pachyderm/pachyderm/vendor/go.pedge.io/lion.(*errorHandler).Handle(0x1266e00, 0x7f3006701050, 0xc8203c65a0)
        /go/src/github.com/pachyderm/pachyderm/vendor/go.pedge.io/lion/defaults.go:37 +0x78
github.com/pachyderm/pachyderm/vendor/go.pedge.io/lion.(*logger).print(0xc82018a070, 0x2, 0xc8203d8300, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/pachyderm/pachyderm/vendor/go.pedge.io/lion/logger.go:221 +0xc9
github.com/pachyderm/pachyderm/vendor/go.pedge.io/lion.(*logger).LogEntryMessage(0xc82018a070, 0xc800000002, 0xc8203d8300)
        /go/src/github.com/pachyderm/pachyderm/vendor/go.pedge.io/lion/logger.go:216 +0x50
github.com/pachyderm/pachyderm/vendor/go.pedge.io/lion/proto.(*logger).Info(0xc820115650, 0x7f3015880550, 0xc8203d82e0)
        /go/src/github.com/pachyderm/pachyderm/vendor/go.pedge.io/lion/proto/logger.go:38 +0xea
github.com/pachyderm/pachyderm/vendor/go.pedge.io/lion/proto.Info(0x7f3015880550, 0xc8203d82e0)
        /go/src/github.com/pachyderm/pachyderm/vendor/go.pedge.io/lion/proto/protolion.go:201 +0x42
github.com/pachyderm/pachyderm/src/pkg/shard.(*sharder).fillRoles.func1(0xc82029e0c0, 0x0, 0x0)
        /go/src/github.com/pachyderm/pachyderm/src/pkg/shard/sharder.go:915 +0x103b
github.com/pachyderm/pachyderm/src/pkg/discovery.(*etcdClient).watchAllWithoutRetry(0xc8200b6290, 0xc82029e060, 0x2e, 0xc8200b0ba0, 0xc82029e090, 0x0, 0x0)
        /go/src/github.com/pachyderm/pachyderm/src/pkg/discovery/etcd_client.go:217 +0x3e6
github.com/pachyderm/pachyderm/src/pkg/discovery.(*etcdClient).WatchAll(0xc8200b6290, 0xc82029e060, 0x2e, 0xc8200b0ba0, 0xc82029e090, 0x0, 0x0)
        /go/src/github.com/pachyderm/pachyderm/src/pkg/discovery/etcd_client.go:61 +0x5c
github.com/pachyderm/pachyderm/src/pkg/shard.(*sharder).fillRoles(0xc820119c20, 0xc8201e0fc0, 0xe, 0x7f3015886e18, 0xc8200b09c0, 0xc8200b0b40, 0xc8200b0ba0, 0x0, 0x0)
        /go/src/github.com/pachyderm/pachyderm/src/pkg/shard/sharder.go:952 +0x18c
github.com/pachyderm/pachyderm/src/pkg/shard.(*sharder).Register.func3(0xc8201e1200, 0xc820119c20, 0xc8201e0fc0, 0xe, 0x7f3015886e18, 0xc8200b09c0, 0xc8200b0b40, 0xc8200b0ba0, 0xc8201e11f0, 0xc8201e1140)
        /go/src/github.com/pachyderm/pachyderm/src/pkg/shard/sharder.go:125 +0xa7
created by github.com/pachyderm/pachyderm/src/pkg/shard.(*sharder).Register
        /go/src/github.com/pachyderm/pachyderm/src/pkg/shard/sharder.go:131 +0x2bf
```

**Comment by peter-edge** [comment]
Oh, that's an interesting one, I'll fix it tomorrow, I think I know the
issue

**Comment by jdoliner** [comment]
Cool, ty. And ty for da pull.

**Comment by peter-edge** [comment]
OK fixed.

The issue was that `map[uint64]bool` is not a valid JSON type, and I was directly calling `json.Marshal` on the message. `uint64s` are not valid JSON keys, only strings. the `jsonpb` package, however, handles this issue, so I added protobuf-specific code to handle this when the data type is `proto.Message`.

The issue actually was probably in protolog too, but would not have appeared on the first level of a message (ie if you had a nested message of this type, it would probably fail).

Let me know if there are any other issues.

**Comment by peter-edge** [comment]
Also note that once this is merged, I'm going to merge github.com/peter-edge/lion-go into github.com/peter-edge/protolog-go, so if you have lion-go checked out, and then do `make update-test-deps` etc, it may fail because the remote path will change. The solution if/when this happens is just to delete `go/src/go.pedge.io/lion` and re-clone.

**Comment by peter-edge** [comment]
There's a couple new features you might want to use:

* `envlion` package - replaces go.pedge.io/pkg/log, sets up logging based on environment variables
* `protolion.LogDebug(), protolion.LogInfo()` - if the log level is above `LevelDebug` or `LevelInfo`, this returns a discard logger, including for `WithField/WithFields/WithContext`. This improves performance when you have situations like `protolion.WithField("key1", "value1").WithField("key2", "value2").Debugln()`, which normally is going to do copy operations on the `WithField` calls

I'm adding more stuff, and will document this eventually.

**Comment by jdoliner** [comment]
Hmm, just tried this. I'm still seeing the same error :(

**Comment by peter-edge** [comment]
Is this just make test? Maybe I can reproduce

**Comment by jdoliner** [comment]
You should get it if you do:

```
make kube-launch
make launch
```

**Comment by jdoliner** [comment]
For me `pfsd` and roler both fail to come up due to the error.

**Comment by peter-edge** [comment]
make launch-kube fails:

```
$ make launch-kube
etc/kube/start-kube-docker.sh
0637a4785c7a1068cb06611e481d2e6c4c3a33895c8161183c3965e72bd10b49
Error response from daemon: Cannot start container 4fa9b63bbe98f74018ab7575e1d181345733334ec0c9fb7da2c7d88f77ae9b50: [8] System error: stat /var/lib/docker/aufs/mnt/4fa9b63bbe98f74018ab7575e1d181345733334ec0c9fb7da2c7d88f77ae9b50/sys/fs/cgroup/cpuset/docker/4fa9b63bbe98f74018ab7575e1d181345733334ec0c9fb7da2c7d88f77ae9b50: no such file or directory
Error: failed to start containers: [4fa9b63bbe98f74018ab7575e1d181345733334ec0c9fb7da2c7d88f77ae9b50]
make: *** [launch-kube] Error 1
$ dc # my docker cleanup alias, deletes all containers
Error response from daemon: Driver aufs failed to remove root filesystem 4fa9b63bbe98f74018ab7575e1d181345733334ec0c9fb7da2c7d88f77ae9b50: rename /var/lib/docker/aufs/mnt/4fa9b63bbe98f74018ab7575e1d181345733334ec0c9fb7da2c7d88f77ae9b50 /var/lib/docker/aufs/mnt/4fa9b63bbe98f74018ab7575e1d181345733334ec0c9fb7da2c7d88f77ae9b50-removing: device or resource busy
Error response from daemon: Driver aufs failed to remove root filesystem 0637a4785c7a1068cb06611e481d2e6c4c3a33895c8161183c3965e72bd10b49: rename /var/lib/docker/aufs/mnt/0637a4785c7a1068cb06611e481d2e6c4c3a33895c8161183c3965e72bd10b49 /var/lib/docker/aufs/mnt/0637a4785c7a1068cb06611e481d2e6c4c3a33895c8161183c3965e72bd10b49-removing: device or resource busy
Error: failed to remove containers: [4fa9b63bbe98 0637a4785c7a]
```

**Comment by jdoliner** [comment]
Yay docker with aufs can't start containers if you add files to them, it's completely broken. You need devicemapper.

**Comment by peter-edge** [comment]
OK it should be fixed now - the ordering of global initialization affected which json marshaller was used.

**Comment by jdoliner** [comment]
Can confirm, fixed. Just merged it.

**Pull request merged**
