### PR TITLE
Fix example input

### PR DESCRIPTION
**Pull request by teodor-pripoae**

### CODE REVIEW

**Comment by jdoliner** [comment]
Looks good to merge.

@teodor-pripoae would you mind signing our CLA? https://pachyderm.wufoo.com/forms/pachyderm-contributor-license-agreement/

**Comment by teodor-pripoae** [comment]
Done, I signed it.

I remember I made another contribution in the past, does this automatically apply to that one ? I'm just checking so you are 100% covered by the agreement.

**Comment by jdoliner** [comment]
Many thanks :D. Merging.

**Comment by jdoliner** [comment]
And yup, still applies. Didn't realize you contributed before.

**Pull request merged**
