### PR TITLE
Make error message resulted from malformed pipeline spec more explicit

### LINKED ISSUE #1904: Failure to marshal a pipeline.json prints an unfriendly error
I set the stdin key to be a string instead of a list and I got this error message.
```
pachctl update-pipeline -f pipeline.json 
json: cannot unmarshal string into Go value of type []json.RawMessage
```

This error message should be friendlier and point to where the json is not according to the pipeline spec.

### PR DESCRIPTION
**Pull request by derekchiang**
Fix #1904

### CODE REVIEW

**Comment by jdoliner** [comment]
LGTM, is there anyway we can get more informative error messages out of failed JSON parsing? I seem to remember us having that at some point but this just seems to be returning the error message directly from `Unmarshal`

**Comment by derekchiang** [comment]
@jdoliner I looked and couldn't find a way to get more informative error messages.

**Comment by thedrow** [comment]
If you upgrade to Go 1.8 you can provide more information. See https://github.com/golang/go/commit/b9fd510cd00b6aa26e2ea7001a07b90ebf97d2ed

**Comment by derekchiang** [comment]
@thedrow hmm I was using Go 1.8 already.  I just upgraded to 1.8.3 (the latest version) and still got the same error messages.

**Comment by thedrow** [comment]
You should check if Struct or Field is empty.
See https://github.com/golang/go/commit/b9fd510cd00b6aa26e2ea7001a07b90ebf97d2ed#diff-4299c3082a8bb7e546723132c992fa4cR120

**Pull request merged**
