### PR TITLE
[MLDM-195] Run CheckStorage after snapshot restore tests

### PR DESCRIPTION
**Pull request by Zhang-Muyang**
exports a function and renames testing package name to avoid circular dependency

### CODE REVIEW

**Review by jrockway — CHANGES_REQUESTED** [review]
I don't think we need to do this refactoring to make CheckVersionCompatability public.  You can just make a new test file that is in package snapshot and that only contains that test.

That said, we don't actually need the pach client in this test.  All you need to do is call chunks.Check.  Where we call fileset.NewStorage, chunks is the 3rd arg.  Just split that out and call directly.

It is unclear to me what Check does with nil start and end.  I think that means check everything?  Please verify though ;)  I would also set readChunks = true.

**Comment by Zhang-Muyang** [comment]
> I don't think we need to do this refactoring to make CheckVersionCompatability public. You can just make a new test file that is in package snapshot and that only contains that test.
> 
> That said, we don't actually need the pach client in this test. All you need to do is call chunks.Check. Where we call fileset.NewStorage, chunks is the 3rd arg. Just split that out and call directly.
> 
> It is unclear to me what Check does with nil start and end. I think that means check everything? Please verify though ;) I would also set readChunks = true.

When start and end are nil, it checks everything

**Review by jrockway — APPROVED** [review]
Looks good!

I think it would have been fine to keep this all in one file.  We don't have a one test case per file policy or anything.  But not a big deal.

**Comment by Zhang-Muyang** [comment]
> Looks good!
> 
> I think it would have been fine to keep this all in one file. We don't have a one test case per file policy or anything. But not a big deal.

Thank you!
Do you want me to put everything in one file? I thought you wanted me to put this test in a separate file.

**Pull request merged**
