### PR TITLE
Updater pix2pix example w/ resource limits

### PR DESCRIPTION
**Pull request by dwhitena**
Updated pix2pix example with working GPUs. Needed to update this with the resource limit changes.

### CODE REVIEW

**Comment by JoeyZwicker** [comment]
LGTM

Has the limits change been documented everywhere else it shows up too?

**Comment by dwhitena** [comment]
@JoeyZwicker no, but I created this to help me remember: https://github.com/pachyderm/pachyderm/issues/2562

**Comment by dwhitena** [comment]
Any idea why CI might be failing here @sjezewski @msteffen. I have restarted several times with the same error.

**Comment by sjezewski** [comment]
Yea, this is the place that CI was getting stuck. It was fixed in [this PR](https://github.com/pachyderm/pachyderm/pull/2556)

So merge in master again and try once more.

**Comment by dwhitena** [comment]
@sjezewski merged in master, but still issues:

```
+kubectl version

+sleep 5

+kubectl version

+sleep 5

+kubectl version

+sleep 5

+kubectl version

+sleep 5

The job exceeded the maximum time limit for jobs, and has been terminated.
```

**Pull request merged**
