### PR TITLE
Change log

### PR DESCRIPTION
**Pull request by jdoliner**
Adds a change log for 1.2

### CODE REVIEW

**Comment by jdoliner** [comment]
Added 2 of those. It already had something about new parallelization features. GF case study seems weird to me since it's not part of the repo. Maybe I should put a blurb about it in the release post though?

I like the contributors idea but I think maybe it'd make more sense to just have a CONTRIBUTORS.md file for that.

**Comment by JoeyZwicker** [comment]
I like the idea of mentioning the GF case study in the blog post

**Comment by JoeyZwicker** [comment]
It's up to you re: contributors. GH technically already shows contributors so it doesn't make sense to have an md file for that. I just noticed a few other Changlogs (rethink being on example) that call our contributors the same way you did for groupcache in the blog post. Ack-ing people also makes them more likely to contribute to the next release and that's something we want to encourage as much as possible

**Comment by JoeyZwicker** [comment]
I still think we should add contributors, but the rest LGTM!

**Comment by jdoliner** [comment]
I agree in principle but am feeling too lazy to get them all together right now. We'll add contributors in the next one.

**Pull request merged**
