### PR TITLE
Fix enterprise check for pipeline autoscaling

### PR DESCRIPTION
**Pull request by msteffen**

### CODE REVIEW

**Review by jdoliner — APPROVED** [review]
LGTM

**Review by Tryneus — APPROVED** [review]
LGTM

**Comment by msteffen** [comment]
Travis passed, so this is ready to merge if the new tests look OK (the circle failures are due to a bunch of failing `DeleteAll()` calls from the beginning of tests—guessing that this is a general 1.x test infra issue)

**Comment by Tryneus** [comment]
Looks like there was a `pachd` crash in the `build-PPS6` bucket:

```
Apr 23 07:27:27 === RUN   TestMissingPipelineSpec
Apr 23 07:27:28     pachyderm_test.go:12119: No error is expected but got pods "pipeline-imputede35b810276e6-v1-lzz97" not found
Apr 23 07:27:28     pachyderm_test.go:12119: current stack:
Apr 23 07:27:28         goroutine 30 [running]:
Apr 23 07:27:28         runtime/debug.Stack(0x2cbb9e0, 0xc0005f9720, 0xc000764ca8)
Apr 23 07:27:28         	/root/go/src/runtime/debug/stack.go:24 +0x9f
Apr 23 07:27:28         github.com/pachyderm/pachyderm/src/client/pkg/require.fatal(0x2d4df00, 0xc0002e5b00, 0x0, 0x0, 0x0, 0x29e3f3e, 0x1f, 0xc000c5def0, 0x1, 0x1)
Apr 23 07:27:28         	/root/project/pachyderm/src/client/pkg/require/require.go:534 +0xdf
Apr 23 07:27:28         github.com/pachyderm/pachyderm/src/client/pkg/require.NoError(0x2d4df00, 0xc0002e5b00, 0x2cbb9e0, 0xc0005f9720, 0x0, 0x0, 0x0)
Apr 23 07:27:28         	/root/project/pachyderm/src/client/pkg/require/require.go:394 +0xec
Apr 23 07:27:28         github.com/pachyderm/pachyderm/src/server.TestMissingPipelineSpec(0xc0002e5b00)
Apr 23 07:27:28         	/root/project/pachyderm/src/server/pachyderm_test.go:12119 +0xa85
Apr 23 07:27:28         testing.tRunner(0xc0002e5b00, 0x2a981a0)
Apr 23 07:27:28         	/root/go/src/testing/testing.go:1123 +0xef
Apr 23 07:27:28         created by testing.(*T).Run
Apr 23 07:27:28         	/root/go/src/testing/testing.go:1168 +0x2b3
Apr 23 07:27:28 --- FAIL: TestMissingPipelineSpec (0.95s)
Apr 23 07:27:28 === RUN   TestFileHistory
Apr 23 07:27:28     pachyderm_test.go:12163: No error is expected but got connection closed
Apr 23 07:27:28     require.go:530: github.com/pachyderm/pachyderm/src/client/pkg/grpcutil.ScrubGRPC
Apr 23 07:27:28         	/root/project/pachyderm/src/client/pkg/grpcutil/error.go:16
Apr 23 07:27:28     require.go:530: github.com/pachyderm/pachyderm/src/client.APIClient.DeleteAll
Apr 23 07:27:28         	/root/project/pachyderm/src/client/client.go:623
Apr 23 07:27:28     require.go:530: github.com/pachyderm/pachyderm/src/server.TestFileHistory
Apr 23 07:27:28         	/root/project/pachyderm/src/server/pachyderm_test.go:12163
Apr 23 07:27:28     require.go:530: testing.tRunner
Apr 23 07:27:28         	/root/go/src/testing/testing.go:1123
Apr 23 07:27:28     require.go:530: runtime.goexit
Apr 23 07:27:28         	/root/go/src/runtime/asm_amd64.s:1374
Apr 23 07:27:28     pachyderm_test.go:12163: current stack:
Apr 23 07:27:28         goroutine 44 [running]:
Apr 23 07:27:28         runtime/debug.Stack(0x2cba8a0, 0xc0004939e0, 0xc000d28e88)
Apr 23 07:27:28         	/root/go/src/runtime/debug/stack.go:24 +0x9f
Apr 23 07:27:28         github.com/pachyderm/pachyderm/src/client/pkg/require.fatal(0x2d4df00, 0xc00077b500, 0x0, 0x0, 0x0, 0x29e3f3e, 0x1f, 0xc000516060, 0x1, 0x1)
Apr 23 07:27:28         	/root/project/pachyderm/src/client/pkg/require/require.go:534 +0xdf
Apr 23 07:27:28         github.com/pachyderm/pachyderm/src/client/pkg/require.NoError(0x2d4df00, 0xc00077b500, 0x2cba8a0, 0xc0004939e0, 0x0, 0x0, 0x0)
Apr 23 07:27:28         	/root/project/pachyderm/src/client/pkg/require/require.go:394 +0xec
Apr 23 07:27:28         github.com/pachyderm/pachyderm/src/server.TestFileHistory(0xc00077b500)
Apr 23 07:27:28         	/root/project/pachyderm/src/server/pachyderm_test.go:12163 +0x14d
Apr 23 07:27:28         testing.tRunner(0xc00077b500, 0x2a98070)
Apr 23 07:27:28         	/root/go/src/testing/testing.go:1123 +0xef
Apr 23 07:27:28         created by testing.(*T).Run
Apr 23 07:27:28         	/root/go/src/testing/testing.go:1168 +0x2b3
```

might be worth looking into before merging.

**Comment by msteffen** [comment]
> Looks like there was a `pachd` crash in the `build-PPS6` bucket:

As strange as it looks, I actually don't think pachd crashed. The debug output included:
```
======================================================================
kubectl get all --all-namespaces
----------------------------------------------------------------------
NAMESPACE     NAME                                                      READY   STATUS      RESTARTS   AGE
default       pod/dash-cf6f47d7d-x7682                                  2/2     Running     0          5m21s
default       pod/etcd-6c65b5bcc9-brf4v                                 1/1     Running     0          5m21s
default       pod/loki-0                                                1/1     Running     0          15m
default       pod/loki-promtail-2f4vt                                   1/1     Running     0          15m
default       pod/pachd-789cd8569-r46jk                                 1/1     Running     0          5m21s
default       pod/pipeline-testreprocesseveryjobdbdcf37d0978-v1-tj8f5   2/2     Running     0          8s
kube-system   pod/coredns-66bff467f8-w6fmg                              1/1     Running     0          17m
kube-system   pod/etcd-b0b5b9401065f7dd                                 1/1     Running     0          17m
kube-system   pod/kube-apiserver-b0b5b9401065f7dd                       1/1     Running     0          17m
kube-system   pod/kube-controller-manager-b0b5b9401065f7dd              1/1     Running     0          17m
kube-system   pod/kube-proxy-7ddjj                                      1/1     Running     0          17m
kube-system   pod/kube-scheduler-b0b5b9401065f7dd                       1/1     Running     0          17m
kube-system   pod/storage-provisioner                                   1/1     Running     1          17m
monitoring    pod/alertmanager-6958d8f8dc-fdlz8                         1/1     Running     0          5m57s
monitoring    pod/grafana-core-6c865bd6c-77llb                          1/1     Running     0          5m57s
monitoring    pod/grafana-import-dashboards-s5nhc                       0/1     Completed   0          5m57s
monitoring    pod/kube-state-metrics-7cd589c9b-xr2hr                    1/1     Running     0          5m56s
monitoring    pod/node-directory-size-metrics-8cvg5                     2/2     Running     0          5m56s
monitoring    pod/prometheus-core-57b7b9bbc-txtc7                       1/1     Running     0          5m57s
monitoring    pod/prometheus-node-exporter-rw4dl                        1/1     Running     0          5m56s
```

(Note 0 restarts for `pod/pachd-789cd8569-r46jk`).

I think it's possible pachd started hanging, or something equivalent to crashing that didn't involve an actual crash? TBH, I have no idea how I would even begin to debug this—the debugging stage does fetch pachd logs, but the only errors I saw in there were various forms of "invalid input" triggered by the test suite (e.g. `2021-04-23T07:32:48Z ERROR pps.API.CreatePipeline {"duration":0.000097556,"error":"input must specify a glob"...`). TBH, I don't know how I would begin to debug this, so I saved the test and debug logs from the testing run and restarted the tests.

**Comment by msteffen** [comment]
I've attached the CircleCI logs from the failed runs, but on re-running they both succeeded (perhaps the late hour is helping, since there may be less contention on the TestFaster machine). Since everything is now green, and my understanding is that this change is blocking two users at the moment, I'm going to merge, but the if we want to revisit the failed run, the logs are below and I think the failed CircleCI run is still available there.

[Circle test logs.txt](https://github.com/pachyderm/pachyderm/files/6374790/Circle.test.logs.txt)
[Circle debug logs.txt](https://github.com/pachyderm/pachyderm/files/6374791/Circle.debug.logs.txt)

**Pull request merged**
