### PR TITLE
No need to upload to s3 anymore.

### PR DESCRIPTION
**Pull request by jdoliner**

### CODE REVIEW

**Comment by sjezewski** [comment]
Yea, we can omit this step, but we do need to make sure we're pushing to the right remote. In fact we should push to both ... `pachyderm/www` because that's the source of truth, and `pachyderm/pachyderm.github.io` for the GH site

**Comment by jdoliner** [comment]
Should we maybe consider having `pachyderm/pachyderm.github.io` be the source of truth from now on? Seems like that might be easier, unless there's some benefit to having them split.

**Comment by sjezewski** [comment]
Yea, we could just do that. We prob want to delete the old repo to prevent confusion. There are a few outstanding issues on the www repo, but maybe there's a way to port them over? Most of them are pretty old, so its not the end of the world if we lose them.

The other optimization I want to do is upload the .deb files someplace (like s3, where we could host a dl.pachyderm.io domain) just because ... right now we overwrite the pachctl.deb file w a large binary and it clutters the history. I'm sure there's a way to take a scalpel to the git history to flatten this file's history but right now everytime we release we put a 10-20Mb bin file in there.

(But that's beyond the scope of this PR of course :-P)

**Comment by sjezewski** [comment]
Also, right now the release process doesn't actually push to the pages remote ... so the deb package doesn't get updated automatically. 

(We hadn't made the change to update the release script since we switched over to gh pages)

**Comment by jdoliner** [comment]
Merging this since I want to do a release w/o pushing to s3

**Pull request merged**
