### PR TITLE
Auth support when reading configs for port forwarding

### LINKED ISSUE #3482: Pachyderm 1.8.3 and 1.8.4 missing oidc dependency, can't auth. 1.8.2 works
**What happened?**:
Upgraded pachctl to 1.8.4 from 1.8.2 (also tried 1.8.3) and pachctl commands won't work with our OIDC enabled cluster
**What you expected to happen?**:
pachctl commands to work
**How to reproduce it (as minimally and precisely as possible)?**:
Install k8s cluster with OIDC auth. Run:
```
$ pachctl port-forward --namespace pachyderm
No Auth Provider found for name "oidc"
```
**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:15:13Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Pachyderm CLI version (use `pachctl version`):
```
sjacobs@neon-07071 ~ $ pachctl version
COMPONENT           VERSION
pachctl             1.8.4
ERRO[0000] Implicit port forwarding was not enabled because the kubernetes config could not be read: No Auth Provider found for name "oidc"
```
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
kubeadm v1.13.2
- Others:
Fix imports:
import (
     _ "k8s.io/client-go/plugin/pkg/client/auth/oidc"
)
[https://github.com/kubernetes/client-go/issues/345](https://github.com/kubernetes/client-go/issues/345)

### LINKED ISSUE #3505: No Auth Provider found for name "gcp"
**What happened?**:

I get the error below when trying to run `pachctl port-forward`:

```
$ pachctl port-forward
No Auth Provider found for name "gcp"
```

**What you expected to happen?**:

Port forwarding should work.

**How to reproduce it (as minimally and precisely as possible)?**:

I've setup pachyderm on my cluster and also am able to run `pachctl deploy google` without issues and see the pods started, it doesn't seem to understand how to handle the gcp authentication hook in the .kube/config

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):

```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-04T04:49:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.6-gke.2", GitCommit:"04ad69a117f331df6272a343b5d8f9e2aee5ab0c", GitTreeState:"clean", BuildDate:"2019-01-04T16:19:46Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Pachyderm CLI version (use `pachctl version`):

```bash
 pachctl version
COMPONENT           VERSION
pachctl             1.8.5
ERRO[0000] Implicit port forwarding was not enabled because the kubernetes config could not be read: No Auth Provider found for name "gcp"
```

- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):

gke

- Others:

```bash
$ kubectl get po,pv,pvc
NAME                         READY   STATUS    RESTARTS   AGE
pod/dash-64d9784867-tnxq7    2/2     Running   0          25m
pod/etcd-0                   1/1     Running   0          25m
pod/pachd-5fc9cf94c8-7qh99   1/1     Running   0          25m

NAME                                                        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                         STORAGECLASS         REASON   AGE
persistentvolume/pvc-afdca041-3473-11e9-ae2b-42010a8000dc   100Gi      RWO            Delete           Bound    default/etcd-storage-etcd-0   etcd-storage-class            25m

NAME                                        STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS         AGE
persistentvolumeclaim/etcd-storage-etcd-0   Bound    pvc-afdca041-3473-11e9-ae2b-42010a8000dc   100Gi      RWO            etcd-storage-class   25m
```

I've followed the Google installation instructions and also have added a clusterrolebinding since I have RBAC enabled, and am able to deploy pachyderm fine, it doesn't seem to handle the `gcp` auth coming from the kubectl config is my guess.

Maybe it isn't handling this properly?

```
$ kubectl config view | tail
  user:
    auth-provider:
      config:
        access-token: <DELETED>
        cmd-args: config config-helper --format=json
        cmd-path: /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/gcloud
        expiry: "2019-02-19T19:49:40Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```

### PR DESCRIPTION
**Pull request by ysimonson**
Fixes #3482 

Fixes #3505

### CODE REVIEW

**Comment by ysimonson** [comment]
No, unfortunately I don't have a cluster handy to test this against. @brokenjacobs would you be up for kicking the tires? I can cut a custom release with this change if you're still seeing errors when building.

**Comment by brokenjacobs** [comment]
No problem! If you could make an OS X build I can test it tonight. Just let me know where to grab it.

**Comment by ysimonson** [comment]
Here it is: https://github.com/pachyderm/pachyderm/releases/download/v1.8.5-e20ac1978f01a451a1ce59ea524113eb9cd6734d/pachctl_1.8.5-e20ac1978f01a451a1ce59ea524113eb9cd6734d_darwin_amd64.zip

**Comment by ysimonson** [comment]
Here it is: https://github.com/pachyderm/pachyderm/releases/download/v1.8.5-e20ac1978f01a451a1ce59ea524113eb9cd6734d/pachctl_1.8.5-e20ac1978f01a451a1ce59ea524113eb9cd6734d_darwin_amd64.zip

**Comment by ysimonson** [comment]
Here it is: https://github.com/pachyderm/pachyderm/releases/download/v1.8.5-3b15373481111ab338f03c171679c591965b3f3b/pachctl_1.8.5-3b15373481111ab338f03c171679c591965b3f3b_darwin_amd64.zip

**Comment by brokenjacobs** [comment]
It works, however there is no way to set a namespace now except on the port-forward command. So port-forward is the only command I can run for now. I would suggest adding the --namespace option to all commands to support this functionality.

**Comment by ysimonson** [comment]
@brokenjacobs Yeah, that's correct. [That concern has been brought up before.](https://github.com/pachyderm/pachyderm/issues/3413) I'm hoping that with all the tweaks of implicit port forwarding that will come out in the next release, it won't feel like it ever gets in the way - even if it doesn't solve all use cases, (including non-default namespaces) since we provide alternatives. Let's see how that shakes out first; I'm hoping to not have to add another global flag to all commands.

**Pull request merged**
