### PR TITLE
Bash completion

### PR DESCRIPTION
**Pull request by derekchiang**
Based off @roylee17's #1238 .  For how it works, see: https://github.com/spf13/cobra/blob/master/bash_completions.md

Currently the completion is fairly rudimentary: it only completes commands, not arguments.  For instance, ideally we'd want to be able to show a list of repos if you press TAB after `pachctl list-repo`.

### CODE REVIEW

**Comment by derekchiang** [comment]
Hmm actually I just realized that this doesn't quite work for `pachctl` installed via `apt-get` or `brew`.  @sjezewski any idea how you might install the completion script via `apt-get`/`brew`?  Basically we just need to pipe the output of `pachctl completition` to a file under `/etc/bash_completion.d`.

**Comment by sjezewski** [comment]
Short term:

If the path we're writing to is always the same, couldn't we ask the user to just run `sudo -E pachctl completion` ? (which we could make output directly to that folder)

Long term:

I think that command should additionally make sure the user owns that folder so that we could update the file as needed as each pachctl command completes.

**Comment by brollb** [comment]
I like how it is done [here](https://github.com/mattallty/Caporal.js#shell-auto-completion) - basically, just print the completion info to stdout and have the user redirect it to wherever he/she wants. Then, in the docs, I would just direct it to the `/etc/bash_completion.d` directory. I like the flexibility and simplicity of this approach to shell completion - thoughts?

**Comment by derekchiang** [comment]
@brollb yeah, I think that should be fine for now.

@sjezewski LGTM this PR?

**Pull request closed without merging**
