### PR TITLE
Pachctl tests and general testing improvements

### PR DESCRIPTION
**Pull request by jdoliner**
This PR adds a few things:

- a basic pachctl test
- some helper testing functions for testing pachctl
- some helper testing functions for quickly checking the state of a pachyderm cluster

### CODE REVIEW

**Comment by derekchiang** [comment]
Fix #710

**Comment by sjezewski** [comment]
This PR doesn't add all the things mentioned in #710 but definitely creates a framework to build out the rest of the tests in #710 

So in the spirit of smaller PRs, if this is passing let's get a review + merge it, even if #710 isn't completed

**Comment by jdoliner** [comment]
@sjezewski could you take a look at this when you have a chance?

**Comment by JoeyZwicker** [comment]
This still need to be merged?

**Comment by jdoliner** [comment]
I'd still kind of like to merge this but I had a lot of trouble getting CI to pass on it. I'll take another swing now that we've made some CI improvements.

**Comment by jdoliner** [comment]
This was closed by a git mishap but it's stale enough that I'm going to leave it closed.

**Pull request closed without merging**
