### PR TITLE
Add docs for VPC and ELBs on AWS

### PR DESCRIPTION
**Pull request by sjezewski**
This has been requested a few times and I've provided support manually a few times ... so time to get this written down.

### CODE REVIEW

**Comment by gabrielgrant** [comment]
My understanding is that we also support setting the address via `~/pachyderm/config.json` -- should that maybe be included in these docs?

**Comment by gabrielgrant** [comment]
Also, to confirm: this does open up the HTTP endpoint on the pachd service too, right?

**Comment by sjezewski** [comment]
Both good points.

I'm not sure we document that config file anywhere, so that should be a separate issue/ticket to document that feature, probably after we address those issues listed.

In terms of ports/hostnames for dash access, I'm not sure how we're going to handle this short of:

- enabling CORS the right way so that cross domain is fine, or
- having a single reverse proxy for all the services we need to expose

I don't think there's a way to have k8s provision a single load balancer for multiple services ... short of doing the reverse proxying ourselves (nginx / etc).

As it stands, this is our current best practice. Since I've been asked this a few times just this week, I'd like to get the docs up. But yea, not being able to login is going to be a dealbreaker for sure.

**Comment by gabrielgrant** [comment]
Split out the config file docs as #3036 

should we open another issue for the dash auth/HTTP download link problem, or do you want to do a bit more investigation to see if it can be supported within the structure of what you're proposing here?

**Comment by JoeyZwicker** [comment]
LGTM We can merge as is for now and come back for some of the other things in this thread

**Comment by sjezewski** [comment]
It seems like the recommended k8s approach is to setup / config an ingress controller

https://blog.getambassador.io/kubernetes-ingress-nodeport-load-balancers-and-ingress-controllers-6e29f1c44f2d

Which is basically what we described above. This should be a new feature request. And this will probably become a dealbreaker for enterprise deployments.

**Pull request merged**
