### PR TITLE
Actually retry instead of blocking indefinitely.

### LINKED ISSUE #1632: Stalled datum stream
We've seen user reports of workers going "zombie" where they'll stop processing datums in the middle of a job and never complete.

### PR DESCRIPTION
**Pull request by jdoliner**
Fixes #1632

### CODE REVIEW

**Comment by derekchiang** [comment]
Jesus

**Comment by derekchiang** [comment]
I fixed a couple other places that have similar code as well.  LGTM.

**Comment by jdoliner** [comment]
I'm actually surprised the linter doesn't catch  this, unless I'm mistaken a single statement `select` is completely useless and likely a bug.

**Comment by derekchiang** [comment]
That's a good point.  Maybe `go vet` would've caught it.  Also maybe the compiler itself shouldn't allow this since like you said it's complete useless.

**Pull request merged**
